### ISSUE TITLE
REST: DELETE /db returns error if a replication is running

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-core#112]
LiteCore throws an error stack for DELETE /db

REST operations done:
```
PUT http://<LiteCoreServIP>:52000/ls_db/ 201
GET http://<LiteCoreServIP>:52000/ls_db/ 200
{"source": "blip://<SG_IP>:4985/db", "continuous": true, "target": "ls_db"}
{"ok":true,"session_id":1}
<Response [200]>
POST http://<LiteCoreServIP>:52000/_replicate 200
{u'ok': True, u'session_id': 1}
GET http://<LiteCoreServIP>:52000/ 200
GET http://<LiteCoreServIP>:52000/ls_db/_changes?feed=longpoll&since=0 404
GET http://<LiteCoreServIP>:52000/_all_dbs 200
DELETE http://<LiteCoreServIP>:52000/ls_db 500
```
The end point `_changes` is invalid, please ignore. The below stack is printed by LiteCore:

https://gist.github.com/raghusarangapani/872806bda72cefc83c0571550dc813a5

**Comment by snej** [comment]
The exception is caught internally and returned from the LiteCore API as an error code, so it's not actually a problem.

The cause of the exception is that the database file can't be deleted because there are other connections open to it, i.e. the one owned by the continuous replication. I'm not sure what CBL 1.x does in this situation; IIRC it closes all the open db handles and then deletes it, and hopefully the replicator stops cleanly

**Comment by snej** [comment]
Just noticed the description is wrong: it's not `_all_dbs` that failed, but `DELETE /db`. (You have to look at the HTTP log message _after_ the error, because the logging is done at the end of the handler.)

**Comment by snej** [comment]
I feel that this behavior is correct — you shouldn't be able to delete a database that's involved in a replication. The error code shouldn't be 500, though ... maybe 403? I looked through the HTTP error codes and couldn't find a more precise one. (423 Locked is possible, but that's really only for WebDAV and has a somewhat different meaning.)

**Comment by snej** [comment]
I went with 423 Locked.
