### ISSUE TITLE
fts query results when using the * wildcard

### ISSUE THREAD

**Issue by jamiltz** [couchbase/couchbase-lite-core#124]
The following query aims to match values that contain a word that ends with "front":

```swift
let hotelSearchQuery = Query
                        .select()
                        .from(DataSource.database(database))
                        .where(Expression.property("description").match("*front"))
for row in try hotelSearchQuery.run() {
    if let ftsRow = row as? FullTextQueryRow {
        "hotelSearchQuery :: \(ftsRow.document.getString("title"))"
    }
}
```

Reference: [FTS3 docs](https://www.sqlite.org/fts3.html#full_text_index_queries)

This query is matching words like 'front', 'beach-front' but not 'seafront'. Is this expected?

**Comment by snej** [comment]
The docs say the `*` is used for token _prefix_ queries. As there's nothing in front of the asterisk, there's nothing to query.

I don't know if FTS can do suffix searches. Since words are stored in an alphabetical index, searching for all the words that end with some string requires an exhaustive linear scan of every word in the index.
