### ISSUE TITLE
Pluggable tokenization / stemming API for FTS

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#147]
Add a C API for tokenizing text, to override the built-in SQLite3UnicodeSN tokenizer. This would take a string and return a set of token strings (possibly with language code(s)?)

This would allow a platform to use a better tokenizer: for example Apple's NSLinguisticTagger, which has very powerful stemming (lemmatization) and can also extract names and proper nouns. Or a platform may have a tokenizer that supports more languages beyond the dozen or so European/Turkish/Russian languages supported by SQLite3UnicodeSN.

(If CBL were to expose this in its own API, then apps could do custom tokenization. For example they might strip out HTML tags or Markdown characters first, or they might return tokens only for hashtags.)

**Comment by rajagp** [comment]
Glad to see this being tracked because I think this is very powerful and developers are going to expect capabilities akin to what the platform natively offers like the `NSLinguisticTagger` which on iOS11 includes powerful [schemes] (https://developer.apple.com/documentation/foundation/nslinguistictagscheme)
Also,  somewhat related to this, would the API be designed such that developers can add their own third party tokenizers (compile time of course). Related request on Couchbase side which may come in handy on CBL as well - Reference :  https://forums.couchbase.com/t/how-to-add-third-party-tokenizer-analyzer-into-couchbase-query-service/13851

**Comment by snej** [comment]
>would the API be designed such that developers can add their own third party tokenizers 

That's exactly what I meant by "a C API for tokenizing text".

**Comment by rajagp** [comment]
Great!

**Comment by atom992** [comment]
need Chinese languages supported also!

**Comment by snej** [comment]
Yes, tokenizing many Asian languages is difficult due to lack of spaces between words. There are some open source libraries that do it, like [Mecab](https://github.com/jordwest/mecab-docs-en) for Japanese, but you need one for every language. A plugin for NSLinguisticTagger would take advantage of the wide array of languages that Apple OS's support.

**Comment by 1Cor125** [comment]
Hello @rajagp. We spoke about this at CB Connect in NY recently. This would be a huge win for CB Lite! Chasing everyone’s FTS wish lists won’t work from a business standpoint for CB but giving us API hooks would be a way of saying: ‘Hey if you need X for your business domain you can write it yourself and plug it in.’ Where I work we publish content in over 900 languages. We also ship html fragments as embedded documents so if we were to seriously consider CB Lite we would also want  to plug in html filters and our own language aware tokenizers. Happy to see the discussion surrounding this.

**Comment by borrrden** [comment]
Migrated to [CBL-118](https://issues.couchbase.com/browse/CBL-118)
