### ISSUE TITLE
Query: LIMIT and OFFSET properties in JSON are ignored

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#172]
Todo in comments indicates this work has not yet been done.

**Comment by snej** [comment]
It would be helpful to give a file/line reference for this comment...
...aha, I think you mean this at QueryParser.cc:240:
```c++
        // LIMIT, OFFSET clauses:
        // TODO: Use the ones from operands
```
The limit/offset in the C4QueryOptions are honored; see the "DB Query" test in c4QueryTest.cc.

**Comment by borrrden** [comment]
Which one is the authority here?  It seems confusing that there are two places that defines skip and offset.  Do they have different meanings?

**Comment by borrrden** [comment]
I am having trouble coming up with the use case for having LIMIT and OFFSET in the JSON parameters.  Having them in the c4queryoptions seems good enough, but in that case we should change the Couchbase Query API to use ulong instead of untyped object.

**Comment by snej** [comment]
It's for nested SELECT expressions.

**Comment by snej** [comment]
* Removed skip and limit from C4QueryOptions and Query::Options
* Instead, "OFFSET" and "LIMIT" properties in a JSON "SELECT" expression are parsed.
* Implemented N1QL ifmissing() and missingif() functions, because they're useful in creating parameter bindings of OFFSET and LIMIT (for example, `LIMIT: ['ifmissing()', ['$limit'], -1]`.)
