### ISSUE TITLE
Continuous replications not stopping

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#179]
Please see https://github.com/couchbase/couchbase-lite-ios/issues/1816 in more detail with unit tests.

**Comment by snej** [comment]
Looks like both those tests involve simple continuous replications. I don't have any regular unit tests for continuous replication in LiteCore because it was difficult to get the tests to complete :) I haven't run the manual tests in a while. I should put some time into getting the tests to be runnable in regular test runs.

**Comment by snej** [comment]
I've just created equivalent unit tests in LiteCore's ReplicatorLoopbackTest, and they pass (i.e. properly go idle.) Those call the C++ API directly, though, so the problem might be at the C API layer.

**Comment by snej** [comment]
I've found an issue where the pull replicator won't stop / go idle, if it gets an error when pulling a revision. Testing the fix now.
