### ISSUE TITLE
Support accessing Query Row's value by key

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#184]
I'm not sure if this's already supported at the LC level or not. With either decision at the CBL API level (key or key and index), we need to be able to get the value by key.

**Comment by snej** [comment]
At the LiteCore level the columns are an array. As we discussed on Friday, the columns don't have meaningful names, not unless there's an `AS` expression (which isn't currently in the spec.)

Naming columns seems like something that's best done at the CBL level, since it doesn't affect the query at all, just the mechanism by which columns are accessed in the public API.
