### ISSUE TITLE
IN ([Expression]) should have N1QL semantics

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#204]
Example usage from the API:

Expression.property(“name”).in(Expression.property(“all_friend_names”));

all_friend_names property has an array value.

**Comment by snej** [comment]
The current implementation of `IN` just maps to SQLite's `IN` — instead it should behave like [N1QL's `IN`](https://developer.couchbase.com/documentation/server/4.6/n1ql/n1ql-language-reference/collectionops.html#story-h2-6), which is an array containment operator.

**Comment by snej** [comment]
Notes on the commit, which isn't merged yet (because it will break CBL unit tests):

* Added an array literal operator, '[]'. Its parameters become the items of the array.
* 'IN' now takes exactly 2 parameters.
   * If the 2nd parameter of 'IN' is an array literal, a SQL "IN" expression is generated as before, e.g. `["IN", a, ["[]", 3, 4]]` turns into `a IN (3, 4)`.
   * Otherwise `['IN', a, b]` turns into `array_contains(b, a)`.
* Updated the JSON query documentation accordingly.

**Comment by snej** [comment]
I've pushed the commit as a branch [feature/query_IN_update](https://github.com/couchbase/couchbase-lite-core/tree/feature/query_IN_update), to test with.
