### ISSUE TITLE
SQLiteQueryEnum::columns() throws "unimplemented" exception

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#214]
https://github.com/couchbase/couchbase-lite-core/blob/ffa37436c34f32fe4eb4f9f0a80570fd140c8f7e/LiteCore/Query/SQLiteQuery.cc#L422-L424

As a bonus I got to try out the new snippet feature!

**Comment by snej** [comment]
This won't ever be called. SQLiteQueryEnum is used only internally. The SQLiteQuery creates one, then copies its results into a SQLitePrerecordedQueryEnum which it returns:

https://github.com/couchbase/couchbase-lite-core/blob/ffa37436c34f32fe4eb4f9f0a80570fd140c8f7e/LiteCore/Query/SQLiteQuery.cc#L463-L475

This may seem a little convoluted, but it was the easiest way to implement running the query all the way to completion immediately (since keeping the statement active isn't viable.)
