### ISSUE TITLE
Query returns the deleted document in case the deleted document is pull-replicated from SG.

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-core#265]
The query returns the deleted document in case the deleted document is pull-replicated from SG.

SG Version: 1.5.0-555
LiteCore: 5e93828
App: Todo sample app

Steps to reproduce/Scenario:

1. Run Sync Gateway with configuration for ToDo.
1. Run ToDo sample which runs LiveQuery.
1. From App, creates one or more documents. These documents will be push replicated to the SG.
1. Manually add `"_deleted":true` entry into the one of document.
1. The replicator pull replcated the document which is marked as a deleted.
1. Live query returns the deleted document as part of query results.  Expectation: the deleted document should not be included in the query result.

NOTE:
- I confirmed the pull replicated deleted document is marked as deleted in local database.

**Comment by snej** [comment]
I don't think the query generator adds any test that checks that the document isn't deleted. Need to fix that...

**Comment by hideki** [comment]
FYI: It seems this issue is only caused if the document is marked the deleted by adding `"_deleted":true` in the document through Sync Gateway.

With the following fix, replicating the deleted document from device to another device works fine.
https://github.com/couchbase/couchbase-lite-core/commit/962c4021e431394d068a1b4582edf6565d3be145

**Comment by snej** [comment]
>Manually add "_deleted":true entry into the one of document.

You did this on SG, correct? And you didn't remove the other properties of the document, so it ends up as a tombstone with other properties still in it? (That would explain the bug: the query sees that those properties match, but doesn't check whether the document is deleted.)

**Comment by snej** [comment]
I can wrap an implicit "and not `_deleted`" test around the WHERE clause of all queries. But if a developer is leaving properties in deleted docs it's presumably because they need to use those properties, and so they might need the ability to query deleted docs. (Maybe "all docs deleted in the last week", or "all docs deleted by Mark"...) That would mean either adding an 'includeDeletedDocs' flag to `C4QueryOptions`, or making it CBL's responsibility to add the "and not `_deleted`" to the JSON query it gives to LiteCore.
