### ISSUE TITLE
2.0: New FTS resulting in no such table: kv_fts_map exception

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-core#268]
Testing on iOS. This may be likely a lite_core issue but it may also be an issue

Created a FTS as follows against a cblite2 DB
``` 
let index:Index = Index.ftsIndex().on(FTSIndexItem.expression(Expression.property("reviews")))
try db.createIndex(index, withName: "reviews")
let searchQuery = Query
        .select(SelectResult.expression(Expression.meta().id),
                SelectResult.expression(Expression.property("reviews")),
                SelectResult.expression(Expression.property("title")))
        .from(DataSource.database(db))
        .where(Expression.property("type").equalTo("hotel")
        .and( Expression.property("reviews").match("friendly")))
        .limit(limit)
```

Running method above results in 
```WARNING: SQLite error (code 1): no such table: kv_fts_map
Exception is no such table: kv_fts_map
```
Tested with
[travel-sample.cblite2.zip](https://github.com/couchbase/couchbase-lite-core/files/1314880/travel-sample.cblite2.zip)
Travel Sample cblite2 

( CC @hideki , @pasin )

**Comment by snej** [comment]
I've run into this too — it happens because the database was created before the version of LiteCore that added the `kv_fts_map` table (this was the indexing API change to support named indexes.)

We could fix it by adding code when opening a db to add the table if necessary, but I figured that since we're still pre-beta there's no urgent need to keep perfect compatibility with existing databases.

@rajagp, you can work around this by opening the database with the `sqlite3` tool and entering:

`CREATE TABLE kv_fts_map (alias TEXT PRIMARY KEY, expression TEXT) WITHOUT ROWID;`

**Comment by rajagp** [comment]
Thanks @snej . That command worked. So assuming that this would be part of migration from 1.x Databases (whenever 2.0 goes beta)

**Comment by snej** [comment]
No, not from 1.x, just from 2.x builds earlier than sometime last month.

**Comment by rajagp** [comment]
Yes, that too (and as you noted, thats probably not a high priority since its pre beta). But if you are on 1.x, wouldn't you need to add the kv_fts_map table as part of the migration to 2.x

**Comment by snej** [comment]
No, the updater already creates a new 2.x database (including all the tables) and adds the documents and attachments to it. The original 1.x database isn't altered, until it's finally deleted at the end of the process.
