### ISSUE TITLE
Installing canned databases

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#27]
We need an API to copy a canned database (probably bundled inside the app) into a regular database location and set it up for use.

Besides simply copying the files, this also involves changing some settings to do with the replicator, like giving the db a new UUID.

**Comment by borrrden** [comment]
## Proposal

Prerequisite:  Only supporting databases made in CBL 1.2+ (currently the case) because of how they are structured (and because 1.1 is EOL, and actually 1.2 will be at the end of August 2017)

SIgnature:  `bool c4db_replace(C4Slice directory, C4Slice pathToReplacement, C4Error* err);`

Steps
------
1. Backup existing database with the same name (if any) by renaming its folder
2. Copy specified `pathToReplacement` to temp directory (I'd want to avoid this on CBL .NET since it is difficult to include a structured folder as an asset and much easier to use a zip which I would then unzip to a temp directory anyway.  Perhaps a read-write check?)
3. Open the database, triggering upgrade if needed (possible failure for pre-1.2 DB here, store that information into `err`)
4. Create new public and private UUID (other steps needed?)
5. Close DB and copy it to `directory`
6. Delete backup

Failure at any point in this process will result in the following:
- Rollback of the entire process (delete the DB from `directory` and restore the backup by restoring its original name)
- Returning `false` and storing error information in `err`

**Comment by borrrden** [comment]
@snej Is this what you are looking for --^ ?

**Comment by snej** [comment]
Thanks! Sorry I put off looking through this.

I think step 1 can be moved to before step 5, since nothing in steps 2-4 affects the old DB. That way if there's a crash before step 5, the old DB is still intact in its original location.

In step 5 I think you meant "_move_ it", not "copy it"?

**Comment by borrrden** [comment]
## Proposal

Prerequisite:  Only supporting databases made in CBL 1.2+ (currently the case) because of how they are structured (and because 1.1 is EOL, and actually 1.2 will be at the end of August 2017)

SIgnature:  `bool c4db_copyExisting(C4Slice sourcePath, C4Slice destinationPath, const C4DatabaseConfig* config, C4Error* err);`

Steps
------
1. Copy specified `sourcePath` to temp directory (I'd want to avoid this on CBL .NET since it is difficult to include a structured folder as an asset and much easier to use a zip which I would then unzip to a temp directory anyway.  Perhaps a read-write check?)
2. Open the database according to `config`, triggering upgrade if needed (possible failure for pre-1.2 DB here, store that information into `err`)
3. Create new public and private UUID (other steps needed?) and close DB
4. Backup existing database with the same name (if any) by renaming its folder
5. Move database from temp location to `destinationPath`
6. Delete backup

Failure at any point in this process will result in the following:
- Rollback of the entire process (delete the DB from `directory` and restore the backup by restoring its original name)
- Returning `false` and storing error information in `err`

**Comment by snej** [comment]
Looks good. There's going to be some redundant copying going on if the new db gets upgraded (the Upgrader class will make a 2nd copy of it for safety purposes), but I don't think it's worth trying to optimize that far!

**Comment by borrrden** [comment]
I agree since this is (usually) a one time thing.  I think it's far more important to focus on good error handling because any mistakes there could result in lost data...and I can't think of a worse symptom than that.

**Comment by snej** [comment]
This has been in for a few weeks; don't know why it wasn't closed.
