### ISSUE TITLE
Replicator in LiteCore

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#3]
Are there plans to add replication here? It would be great to have Couchbase Lite for e.g. embedded devices or C++ applications.

**Comment by snej** [comment]
It would be. The problem is that networking is pretty platform-dependent, especially when you include higher-level things like TLS, proxying, HTTP (and HTTP/2!) or WebSocket client libraries, reachability determination, network-changed notifications, P2P discovery ...

For example, we could use POSIX socket APIs from C++ and cover Linux, BSD and Apple platforms. But Apple's higher level APIs like NSURLSession have some very useful features, like automatically switching traffic between WiFi / cell / Bluetooth and routing through proxies using the system proxy configuration.

One approach we've talked about is implementing the replicator but leaving the actual networking as hooks to be implemented by platform code. So there might be an abstract "send HTTP request" hook, one of whose parameters is a callback function that returns the response data back to LiteCore. This sounds simple, but I think we'd be implementing the equivalent of an HTTP API, and looking at something like NSURLSession.h, you can see that those get big and complex.

**Comment by adamski** [comment]
I see. I'minterested

**Comment by adamski** [comment]
I'm interested in porting an app to Sailfish OS, which is based on C++. Looking at their [docs](https://sailfishos.org/wiki/Core_Areas_and_APIs#Networking), they use a library called [connman](https://01.org/connman) for networking.

In terms of desktop C++ apps, on Mac we can easily interface with the Couchbase Lite via Objective-C++ and on Windows via .NET interop (or in both cases via the REST API). Linux is a bit more tricky..

**Comment by snej** [comment]
Since Sailfish is a Linux distro, LiteCore as it is now should run fine on it. Well, it may not build _at the moment_ because I've made a ton of changes on macOS in the past few months, and we're only just starting to fix the cross-platform issues (@borrrden is pretty close to having it working again on Windows.) The Linux build doesn't break as often because the compiler and the APIs are more similar.

Anyway. No promises about adding a replicator to this layer. We're still working out the overall architecture of Couchbase Mobile 2.0. Things should be more solid by our developer conference which is about 2 months from now.

**Comment by borrrden** [comment]
I was wondering about this myself actually.  I am very wary of "implementing the replicator but leaving the actual networking as hooks to be implemented by platform code."  That means that every single request would have to cross the managed - unmanaged boundary twice for Java and C# and other managed languages (once to get the data for the request and once to set it for the response).  

So far I've noticed that one of the biggest hotspots for CBForest on .NET is marshalling strings (about 16% of CPU time on some performance tests I did).  Each string marshal consists of:

To unmanaged:
Allocate managed byte array of proper size
Serialize string into UTF-8 bytes into that array
Pin the section of memory
Send the address to unmanaged

To managed:
Allocate a new managed string object using a pointer to the given bytes (this will copy / process them into UTF-16 internally)

The fewer crosses of the boundary the better.  However, I've been writing this note for about 30 minutes now and I still haven't thought of a better way other than moving replication out to different platforms.

**Comment by adamski** [comment]
Perhaps, in order to support C++ apps directly, a seperate C++ module for replication and networking could be written, e.g. using the [connman](https://01.org/connman) library. I know its another platform to support. If I was to have a go at starting this, where would be a good place to look to start translating the code? (Mainly out of interest, I won't have time to look into this properly for a while yet!)

**Comment by snej** [comment]
There's no correlation between the language an app is written in and the language used to implement replication. So if replication were implemented with connman, LiteCore could be used from any language that has bindings.

The replicator is the most complex part of Couchbase Lite, and we haven't given any real thought yet about how to modularize it by separating the networking implementation. I don't think there's any real work that you could start doing yet. You can look at the existing implementations in any of the Couchbase Lite repos: couchbase-lite-ios or couchbase-lite-java-core or couchbase-lite-net.

**Comment by snej** [comment]
Replicator was added to LiteCore recently.
