### ISSUE TITLE
Possible to make FLSharedKeys thread safe?

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#317]
From https://github.com/couchbase/couchbase-lite-ios/issues/1967, the `FLSharedKeys` is shared by all documents (both mutable / immutable) in the database. Also we assume that the immutable documents are thread-safe by its read-only nature. To avoid the putting a shared lock in Document and MutableDocument to make (Immutable) Document thread-safe, would it be possible to make `FLSharedKeys` thread safe?

**Comment by snej** [comment]
The mutable-Fleece C++ classes aren't thread-safe even if the document isn't being mutated, because the `const` methods can mutate internal data -- for example, MDict caches values in an internal std::map the first time they're accessed.

Even if the `const` methods didn't mutate anything, you'd still need to use locks around them, because the immutable methods might be called on a mutable instance. For example, a CBLMutableDictionary's `removeValueForKey:` method might be called concurrently with its inherited `-count` method, meaning that `-[CBLDictionary count]` needs to lock.

I think this means that you need to wrap locks around all Array / Dict / Document operations even in immutable classes. But I'm not 100% confident of that. Do you see any problems with my reasoning? 🤔

**Comment by pasin** [comment]
@hideki and @borrrden please see @snej last comment. I have chatted with @snej and we will need to lock Array / Dict / Document both read / write operations. The current idea is to lock over the database object. If there is no database object, it will lock itself. We could discuss about the solution.
