### ISSUE TITLE
Need an ability to know if the value of a column in C4QueryEnumerator.columns is missing or not.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#342]
The issue is originally from https://github.com/couchbase/couchbase-lite-ios/issues/1982. 

CBLQueryResult implementation is based on an array of projected result values which cannot be differentiated if the value is null or missing. As a result, QueryResult.toDictionary() currently preserves all of the projected keys/columns, which is not correct. We would like to be able to know if the value is actually null or missing to be able to decide to preserve or not preserve the key.

**Comment by borrrden** [comment]
This is overlooking the next problem:  What can we do about this distinction inside of CBL queries?  Do we need to reintroduce a "null" class (a la `NSNull`?) because otherwise how can we represent this value when we ask for it by column name or position?  This is the original reason that we decided to merge these two (missing / null) into one.

**Comment by pasin** [comment]
We have discussed this through. It's better to not introducing a new value type like MISSING or NULL. Accessing the CBLQueryResult by index will just return null so if users want to know if it's missing or not, users will need use CBLQueryResult.contains(key) to check if the key exists or not.

**Comment by borrrden** [comment]
@snej Do you have any idea of how this would be possible?  By the time the results are turned into fleece, missing and null are already merged into one...so fleece cannot distinguish between missing and null.  It seems to me that to do this we'd have to add another fleece type for missing.  We can't just leave that value out because at that point we won't know which value was removed (query results are *ARRAYS* with keys mapped to each index).

**Comment by snej** [comment]
The missing vs null state is available from the SQLite query result API; it gets lost when the columns are written to a Fleece array by SQLiteQueryRunner. So that's where the change is needed.

Brainstorming possible solutions:

1. Use a placeholder value to denote 'missing' (but what? Any valid Fleece value can appear in a query result already.)
2. Add a bitmap that indicates which array elements are valid (i.e. an integer whose bits correspond to column numbers.)
3. Add an `undefined` value to Fleece. Technically it wouldn't be hard, but I don't like the idea because `undefined` is supposed to mean the absence of a value.
4. Store the row as a Fleece dictionary not an array. The problem here is that we don't necessarily have meaningful column names to use as keys. (We could just use "0", "1", "2"...) It's also somewhat slower to access.

**Comment by borrrden** [comment]
4 also came to mind for me, and actually meaningful column names are undesirable here or else we might lose positional access (order of keys is not guaranteed in a dictionary right?).  So I think it's either numbered or nothing.

Fleece already has an "undefined" type right?  Could we make use of that?  Undefined is supposed to mean the absense of a value, but isn't that exactly what it would indicate here?

**Comment by snej** [comment]
No, Fleece only has `null` in the Java sense. Its equivalent of `undefined` is a NULL pointer in the C/C++ API, but you can't store that in a collection (just like in JavaScript, IIRC.)

There's room in the data format to add another "special" value alongside `true`, `false` and `null`. It would just cause all kinds of ripples throughout the API, and might have unintended side effects on existing client code.

**Comment by borrrden** [comment]
I see.  In that case here it my takes on the four options:

1. I thought about this route a lot as well but nothing clever comes to mind.  
2. This seems like it might be the least intrusive way to allow this
3. A bit too heavy I think
4. Second best way, either by changing to dictionary, making extra array entries (1, value, 3, value, etc) or somehow prefixing the array entries, or otherwise marking them

**Comment by snej** [comment]
I think I'm going to go with 2 (the bitmap).
