### ISSUE TITLE
Replication fails with error "Invalid sequence ID in ‘since'"

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#388]
### Environment:
CBL - 2.0- DB 22 -> ios build 574, Android 299
client -> ios, Android
sg -> 2.0.0- 773

### Steps to reproduce :
1. Set up sync-gateway and sg_accel 
2. Create docs in SG.
        3. pull replication to CBL with continuous
        4. tombstone doc in sG.
        5. wait for replication is idle.
        6. Verify that tombstone doc is deleted in CBL too.

### Result : 
Throwed an error while replication happens at step 5 
``` 2018-02-03 14:32:14.006352-0800 CBLTestServer-iOS[2213:3010783] CouchbaseLite Sync Info: CBLReplicator[<* URL[ws://192.168.33.11:4984/db]] is idle, progress 0/0, error: Error Domain=CouchbaseLite Code=35 "Invalid sequence ID in 'since': "1-0::842.1"" UserInfo={NSLocalizedDescription=Invalid sequence ID in 'since': "1-0::842.1"}```

### CBL logs : 
[del-doc-sg.zip](https://github.com/couchbase/couchbase-lite-core/files/1692291/del-doc-sg.zip)

### SG logs : 
[sg-del-doc.txt](https://github.com/couchbase/couchbase-lite-core/files/1692295/sg-del-doc.txt)

### sg-accel logs : 
[sg-accel-sg-del-doc.txt](https://github.com/couchbase/couchbase-lite-core/files/1692293/sg-accel-sg-del-doc.txt)

**Comment by sridevi-15** [comment]
It is not regression.

**Comment by snej** [comment]
The error message "`Invalid sequence ID in 'since': "1-0::842.1"`" comes from Sync Gateway (blip_sync.go:189) LiteCore sends a `subChanges` request to SG, which returns this error in the response.

This looks like an SG bug. @tleyden, should `"1-0::842.1"` (with quotes) be a valid sequence ID? `ParseSequenceIDFromJSON()` is rejecting it. Presumably this ID came from a checkpoint.

@sridevi-15, I can't open `del-doc-sg.zip`. It seems to be a Word document; I don't have Word, and Pages can't open it. Can you resave it as plain text, please?

**Comment by snej** [comment]
@sridevi-15, the logs show that two replications were run (and starting the second one is what fails), but your description says there's only one replication, started in step 3. Can you give more details of what's going on?

**Comment by tleyden** [comment]
> This looks like an SG bug. @tleyden, should "1-0::842.1" (with quotes) be a valid sequence ID? Presumably this ID came from a checkpoint.

@snej I recently ran into that while debugging, and thought the extra quotes were causing an issue, but it turned out to be a red-herring and unrelated to the quotes.  Also, I can see in our unit tests that we have specific tests to handle extra quoted strings:

https://github.com/couchbase/sync_gateway/blob/67c2c323cf45612e2d0bef60b764bdfc4447977c/db/sequence_id_test.go#L84

**Comment by snej** [comment]
The quotes aren't extra, they're required -- the sequence ID is encoded as JSON.

**Comment by tleyden** [comment]
I'm moving this to https://github.com/couchbase/sync_gateway/issues/3283
