### ISSUE TITLE
Common-ancestor body is missing when conflict is detected

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#402]
When a pushed revision fails with a 409 Conflict, the replicator inadvertently deletes the body of the parent revision, making a future 3-way merge impossible.

1. Revision 3-aaaa exists on both client and server.
2. Client updates to 4-bbbb.
3. Server updates to 4-cccc.
4. Client pushes 4-bbbb to server, which rejects it with a 409 status.
5. Client pulls from server, receives 4-cccc and adds it locally.
6. Client reads the three conflicting revisions, but finds that 3-aaaa no longer has a body.

The problem occurs in step 4 -- `DBWorker::markRevsSynced` is called as soon as the new revs are sent in a `proposeChanges` message, and by setting the Synced flag on the doc it has the effect of marking the current revision (4-bbbb) as  the current server revision, whose keepBody flag will be set, and clearing the keepBody flag of its parent 3-aaaa. It really shouldn't be called until after the revision is known to have been saved on the server.

**Comment by kuscsik** [comment]
Hi @snej ,

I'm not exactly sure if this is related to this bug but I get a conflict in updating of documents under the following conditions on Android couchbase lite:

1.  Pull/Push replicator enabled.
2.  The application creates document X. Which is updated and saved periodically (constant period). The save is done as follows: If the document exists in the database,  it is converted to a MutableDocument which is updated with a new data and saved to the database. If the document does not exist, a new document is created.
3. The phone is switched to offline mode (flight mode), the document still updated periodically.
4. The application is stopped and flight mode disabled.
5. The application is started again, the document updated periodically.

**Expected behavior**: after step 5 the document should be updated on the couchbase server but it fails to update permanently. Couchbase lite reports a document conflict. Tried to register conflict callbacks for replicator/document which get never called.

The issue is not 100% reproducible, but eventually, after few repeats of steps 3-5, application always ends up not able to update the remote device.

couchbase-sync server: **master** branch 28.February
couchbase-android-lite: **master** branch 28. February.

Couchbase sync server config:

SSL enabled.
Replicator authentication enabled.
Extra config options for buckets:
```
      "compressResponses":false,
      "unsupported": {
        "replicator_2":true
      }
```

**Comment by snej** [comment]
@kuscsik: That sounds like #436, a bug that I discovered & fixed earlier today. Basically, if you'd updated a doc 20 times or more since the last push, subsequent pushes would fail.

**Comment by kuscsik** [comment]
Hi @snej,

yes, exactly that is the behavior I saw. Thanks!

**Comment by snej** [comment]
Recent changes should have resolved this: revisions are not marked as "synced" until they've actually been pushed to the server.
