### ISSUE TITLE
Add unit test to confirm WAL file doesn’t grow without bound

### ISSUE THREAD

**Issue by snej** [couchbase/couchbase-lite-core#414]
In .NET 1.4.1 we have [a report](https://github.com/couchbase/couchbase-lite-net/issues/973) of the WAL file growing without bound (GB+) and never shrinking even after compacting and closing the database; this shouldn't happen.

There's a gist attached to that issue showing a very simple test case. We should port this to the LiteCore API and make it a unit test confirming proper behavior of the WAL.

FYI, [WAL documentation is here](https://sqlite.org/wal.html).

**Comment by borrrden** [comment]
The result of this test in LiteCore is this when following the same create 1000, purge 500, compact, close procedure:

> WAL size 0.000000 MB at start
WAL size 1.559898 MB after add
WAL size 2.133553 MB after purge
WAL size 2.133553 MB after compact
WAL size 0.000000 MB after close

Compact has no effect on the WAL size, because in 2.0 there doesn't seem to be any WAL operations inside of compact (e.g. wal_checkpoint).  However, the assertions that WAL is <= previous WAL after compact and after close holds true.  Is that a good enough metric?

**Comment by snej** [comment]
Looks good. Can you check this in as a unit test?

**Comment by borrrden** [comment]
Sure...what's the most appropriate place do you think?  I put it into c4DatabaseTest.cc but it adds the need for query and fleece functionality so it might be the wrong place.

**Comment by snej** [comment]
This test needs to run queries? Can you take that part out? c4DatabaseTest seems the most appropriate place.

**Comment by borrrden** [comment]
If we follow the original implementation, which uses all documents query to get its list of IDs to purge, then yes.  I thought that this might have introduced an area that would prevent WAL merge (transaction for query).  I can easily take it out though.

**Comment by borrrden** [comment]
Migrated to [CBL-53](https://issues.couchbase.com/browse/CBL-53)
