### ISSUE TITLE
Fix the error code reported when sub changes message is ignored

### ISSUE THREAD

**Issue by rajagp** [couchbase/couchbase-lite-core#537]
Please address the TODO in

 https://github.com/couchbase/couchbase-lite-core/blob/8affd23683f0f19d667953297ecf06899e884e70/Replicator/Pusher.cc#L93
The error code of conflict can cause confusion as reported in these log messages
```
2018-06-29 17:25:49.516893+0530 Demo[569:102617] CouchbaseLite Sync ERROR: {Pull#2}==> litecore::repl::Puller ->x-msg-endpt:///
2018-06-29 17:25:49.517547+0530 Demo[569:102617] CouchbaseLite Sync ERROR: {Pull#2} Got error response: LiteCore 8 ‘I’m already pushing’
```

**Comment by snej** [comment]
This means the replicator's push side is already active and then gets told to start again. This could happen if peer A starts a push to B, and then B on the same WebSocket/replicator decides to pull from A. I don't know how this could happen, since the side that receives the WebSocket connection (the "server" side) always acts passively.

A better error code might be 501 Not implemented. But regardless, I'd like to know how this situation happened, since I don't think it should be possible to reach it.

**Comment by rajagp** [comment]
Yeah- not sure of the right code. Lets just do 501 for now and update to something else when we get details of the error case. I will try and get details of specific scenario - but what I know is that this was a peer-to-peer implementation that wasn't quite done right resulting in a peer sending doc to a peer from where they just received the data . So while the reason they got into this state is an application level bug, the error that was logged  was not intuitive.

**Comment by borrrden** [comment]
Should I go ahead with the 501 or should we get more info first?
