### ISSUE TITLE
Conflict error in CBL P2P push replication when using different target database UID

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#541]
P2P replication two local databases (db and otherdb) resulted to 409 conflict error when pushing a document in the following scenario:

1. Add “doc1” to otherdb.
2. Create P2P pull replicator to pull doc1 from otherdb to db.
3. Modify doc1 on db.
4. Create P2P push replicator to push changes from db to other _BUT use a different UID_ when setting up the message endpoint.
5. Result in 409 Conflict error.

**Unit Test**
```Objective-C
- (void)testP2P409Error {
    [CBLDatabase setLogLevel:kCBLLogLevelVerbose domain:kCBLLogDomainReplicator];
    CBLProtocolType protocolType = kCBLProtocolTypeMessageStream;
    
    CBLMutableDocument* mdoc = [CBLMutableDocument documentWithID:@"doc1"];
    [mdoc setString:@"otherdb" forKey:@"name"];
    [self saveDocument:mdoc toDatabase:otherDB];
    
    CBLMessageEndpointListenerConfiguration* config = [[CBLMessageEndpointListenerConfiguration alloc] initWithDatabase:otherDB protocolType:protocolType];
    CBLMessageEndpointListener* listener = [[CBLMessageEndpointListener alloc] initWithConfig:config];
    
    // PULL
    MockConnectionFactory* delegate = [[MockConnectionFactory alloc] initWithErrorLogic:nil];
    CBLMockServerConnection* server = [[CBLMockServerConnection alloc] initWithListener:listener andProtocol:protocolType];
    CBLMessageEndpoint* target = [[CBLMessageEndpoint alloc] initWithUID:[NSString stringWithFormat:@"test1"] target:server protocolType:protocolType delegate:delegate];
    CBLReplicatorConfiguration* replConfig = [[CBLReplicatorConfiguration alloc] initWithDatabase:_db target:target];
    replConfig.replicatorType = kCBLReplicatorTypePull;
    [self run:replConfig errorCode:0 errorDomain:nil];
    AssertEqual(_db.count, 1UL);
    
    mdoc = [[_db documentWithID:@"doc1"] toMutable];
    [mdoc setBoolean:YES forKey:@"modified"];
    [self saveDocument:mdoc];
    
    // PUSH
    server = [[CBLMockServerConnection alloc] initWithListener:listener andProtocol:protocolType];
    target = [[CBLMessageEndpoint alloc] initWithUID:[NSString stringWithFormat:@"test2"] target:server protocolType:protocolType delegate:delegate];
    replConfig = [[CBLReplicatorConfiguration alloc] initWithDatabase:_db target:target];
    replConfig.replicatorType = kCBLReplicatorTypePush;
    [self run:replConfig errorCode:0 errorDomain:nil];
    AssertEqual(_db.count, 1UL);
    
    CBLDocument* savedDoc = [otherDB documentWithID:@"doc1"];
    Assert([savedDoc booleanForKey: @"modified"]);
}
```

**Error:**
```
ERROR: {Push#12} Proposed rev 'doc1' #2-72b9eda328fb3cefba3661abf41c38526ee368ab (ancestor (null)) rejected with status 409
```

**Log:**
https://gist.github.com/pasin/4fd6dd67af4eaae3a44441d4a78d5fe0

**Comment by pasin** [comment]
There was no issues when testing the same with DatabaseEndpoint to replicate b/w two local databases.

**Comment by borrrden** [comment]
Some more analysis:

This 409 comes during the DBWorker::findProposedChange method

```
int DBWorker::findProposedChange(slice docID ("doc1"), slice revID ("2-72b9eda328fb3cefba3661abf41c38526ee368ab"), slice parentRevID (null),
                                     alloc_slice &outCurrentRevID)
``` 

A generation 2 revision comes in without a parent somehow, instead of the correct parent which is found as the current doc (1-2146fa2984d485b355bc81d9fe0b42f0bf9cde26).  How did it go missing?

**Comment by borrrden** [comment]
Here in `sendChanges` in the pusher:

```
if (_proposeChanges) {
                enc << change->docID << change->revID;
                if (change->remoteAncestorRevID || change->bodySize > 0)
                    enc << change->remoteAncestorRevID;
```

`change->remoteAncestorRevID` is null when I think it should not be.  The question is where is it normally set?

**Comment by borrrden** [comment]
This issue affects Sync Gateway as well in rare circumstances.  Basically it has to do with the way that endpoints are mapped to opaque IDs for use with replicators.  If the same endpoint is mapped to two or more of these IDs, then this issue happens because all history information about what was previously sent is lost and the replicator behaves as if it is talking to a brand new endpoint.

**Comment by djpongh** [comment]
@borrrden @snej will this be needed for 2.1?

**Comment by snej** [comment]
If I understand rightly, then in its simplest form this can occur whenever:
* databases A and B have the same document (same ID and history)
* A has never replicated with B
* A makes a change to the doc
* A pushes to B

A has no idea what B's current revision of the doc (if any) is. Since the most likely case is that B doesn't have the doc at all, A does not send a previous-revID in the `proposeChanges` request. That's why `change->remoteAncestorRevID` is null during `sendChanges`.

But in this case B _does_ have the document, so it returns a 409 Conflict. Again, this is correct. Along with the error it sends its current revID.

What _should_ be happening is that A then looks at B's current revID, sees that it's an ancestor of the rev it's trying to push, and so sends a `rev` message containing the body, with B's revID as the parentRevID. Sounds like we're missing the logic for this?

**Comment by snej** [comment]
> Since the most likely case is that B doesn't have the doc at all, A does not send a previous-revID 

Hm, I just realized that a different solution to this could be to change the above logic, and have A send the parent revID. If B doesn't have the doc at all, it should be OK since it wants the doc regardless of what its history is. If B does have the doc, and has the previous revID, then the revIDs will match and everything's cool.

**Comment by borrrden** [comment]
What if the revision is two generations ahead though?  Then it seems like the second approach won't work again since only one previous revision is sent.

**Comment by snej** [comment]
In that case it would end up at the "what _should_ be happening..." bit from above.
So the crux of the problem seems to be that it isn't happening...

**Comment by snej** [comment]
IMHO this isn't bad enough to hold up 2.1. It's an uncommon situation, and most of the time it's something that can and should be avoided by using a consistent UUID for the replicator endpoint. But it'd be good to get it into the next release.

**Comment by borrrden** [comment]
Migrated to [CBL-127](https://issues.couchbase.com/browse/CBL-127)
