### ISSUE TITLE
Add try/catch to c4socket_received to prevent crash / abort

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#562]
From @snej's comment in https://github.com/couchbase/couchbase-lite-ios/issues/2196:

> c4socket_received's implementation doesn't have a try/catch block, so throwing an exception causes an abort/crash ... we should fix that in LiteCore.

From https://github.com/couchbase/couchbase-lite-ios/issues/2197, there could be an exception thrown from `c4socket_gotHTTPResponse` as well. We should consider add try/catch there as well.

**Comment by pasin** [comment]
@snej I want to add try/catch to c4socket_received and c4socket_gotHTTPResponse, I need your input:

1. Is [this](https://github.com/couchbase/couchbase-lite-core/blob/master/Replicator/c4Socket.cc#L185) the right level to add the try/catch.
2. When getting an exception, is it right to call c4socket_closed(socket, error) to close the socket?

**Comment by snej** [comment]
1. Yes.
2. No, because that's only called after the platform code has closed the underlying socket, so if we call it directly that close won't happen. I think instead calling C4Socket's `requestClose` or `close` would be appropriate.

Use the utilities in c4ExceptionUtils.hh to handle the exception.

**Comment by snej** [comment]
@pasin Is this issue fixed now?

**Comment by pasin** [comment]
Yes, we can close it.
