### ISSUE TITLE
Android: copying prepackaged db and upgrading db may not work with external storage

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#575]
The logic to copy prepackaged db or upgrade db involves moving files (via rename) from temp directory (system storage) and a target directory which could be an external storage (e.g. SD Card). The rename will fail with the EXDEV error code if that condition happens.

**Comment by snej** [comment]
This can happen on desktop platforms too, of course.

Apple platforms have an API for locating a temp directory that's on the same filesystem volume as a given path. (IIRC we used it in 1.x.) Is there something comparable for Android?

**Comment by pasin** [comment]
I have been searching a Native API to get a temp directory on Android but I couldn't find one. Some people suggested to use `/data/local/tmp` but recently some people encountered the issue that the directory is not accessible on some android devices. CBL Android currently sets the TMPDIR env variable when opening the database pointing to the application's [cache dir](https://developer.android.com/reference/android/content/Context#getCacheDir()) as that seems to be the most reliable location that can be used as temp for Android.

After discussion this with @borrrden, I'm thinking to add a fallback logic at [FilePath::moveTo(to)](https://github.com/couchbase/couchbase-lite-core/blob/5da4cc825021bb90be591ae4ab835be201333a0a/LiteCore/Support/FilePath.cc#L585-L602) to do copy&delete when getting the EXDEV error. I tested the fallback logic and it worked.

**Comment by snej** [comment]
Copy/delete isn't atomic, though. That means it will destroy the database on upgrade if the copy fails, e.g. due to disk-full. As a workaround you'd have to first copy the new file to somewhere on the same filesystem as the destination, then do an atomic move to replace the old file ... but if you're doing that, then it's simpler & faster just to create the new file on the destination filesystem in the first place.

**Comment by borrrden** [comment]
I suppose that means that the Java logic must remain, and be ported to .NET to inform LiteCore of the proper temporary location.

**Comment by pasin** [comment]
@borrrden I think that is the simplest solution. Otherwise, we will need to be very be careful to use the temp dir on LiteCore. If somehow it doesn't work, we can rethink about the solution.

**Comment by snej** [comment]
Sounds like Android has a Java method to get the per-filesystem temp dir?

Hm, maybe LiteCore could declare a callback function for this purpose, something like 

```C
extern C4SliceResult (*C4GetTempDirHook)(C4String forPath);
```

Then the `FilePath` class could call it if it's set, otherwise defaulting to the current behavior.

Or could the JNI code in the Android build of LiteCore declare a C++ function for this that uses JNI to call the Java method? Then FilePath could call that function.

**Comment by pasin** [comment]
Android doesn't allow to get the temp directory per file-system based on the given path (I couldn't find it). Android just allows to get a default application temp directory (called cache directory) which is on android's device file system. 

What CBLAndroid is doing now is setting `TMPDIR` environment variable to use either the application's cache directory OR the user's custom database directory based on what set to DatabaseConfiguration.directory. This solution is weak as the TMPDIR could be changed based on the last call to set the `TMPDIR` variable and may not be working if users have multiple databases running on different file systems at the same time. 

We could discuss about this morning during cross-platform.

**Comment by snej** [comment]
Is it setting `TMPDIR` just to change the behavior of `FilePath::tempDirectory()`? 😬 That's definitely not good.

**Comment by borrrden** [comment]
Put some rudimentary work for this on `fix/575_externalStorage` branch

**Comment by pasin** [comment]
Great! Will check it out and test on Android.
