### ISSUE TITLE
Support Meta.expiration for querying by using document's expiration date.

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#599]
This is one of the requirements in the TTL PRD.

**Comment by snej** [comment]
OK, I will add an `_expiration` meta-property. I imagine the value should be an ISO-8601 UTC string.

**Comment by snej** [comment]
NOTE: The value of `["._expiration"] is an integer (milliseconds since Unix epoch), not a string, because that's the form in which it's stored in the database. You can convert it to a string by passing it to the `millis_to_utc()` function. Or you can convert a date string to a comparable integer by passing the string through `str_to_millis()`.
