### ISSUE TITLE
Factor EE open source items into separate files

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#603]
Use the header from the closed source items to indicate that it is *not* an open source candidate.

**Comment by snej** [comment]
I just checked that all nontrivial code bracketed by `#ifdef COUCHBASE_ENTERPRISE` is in separate files already. We only need to update the license text in those files ... but to what?

**Comment by borrrden** [comment]
Huh, it looks like the LiteCore-EE repo was never updated with the correct headers either.  See [here](https://github.com/couchbaselabs/couchbase-lite-net-ee/blob/master/src/Couchbase.Lite.Enterprise/API/Database/EncryptionKey.cs#L1-L15) for a reference of what to add.

**Comment by snej** [comment]
@borrrden Isn't that a different situation? That code is confidential, not public.

**Comment by snej** [comment]
@djpongh -- could you find out what the header text on the EE files ought to be? It's a weird situation because the code is still open, we just don't support people building & using it. One possibility is GPL, which would effectively prevent anyone from building it into a commercial product. (But it's an interesting question whether that license applies to a CE build since it's technically compiled, even if it doesn't do anything...)

**Comment by borrrden** [comment]
I asked that they make a header for this use case, just in case the files in that repo were ever open sourced one day, and this is what they gave me.
