### ISSUE TITLE
c4doc_get should return null when the document was expired

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#640]
Based on a requirement in the PRD that "Request for a document that has expired should return nil", this feature could be either implemented on LiteCore or CBL but it seems reasonable to implement in LiteCore?

**Comment by borrrden** [comment]
How could this be tested at the CBL level?  You'd need a test that runs after the next expiration date but before the next expiration timer.  On .NET that's a resolution of about 14 milliseconds or so.

**Comment by snej** [comment]
@rajagp and I discussed this during the PRD review, and IIRC we decided against this because it creates situations where a query will return data from a document (like its ID) but if you get the document with that ID you fail.

(And the reason we decided not to make queries ignore expired documents is that it adds an extra test of the `expiration` property to every query, which will slow it down somewhat.)

**Comment by borrrden** [comment]
Since this is in the Cobalt milestone now, are we going to do this?

**Comment by borrrden** [comment]
Migrated to [CBL-197](https://issues.couchbase.com/browse/CBL-197)
