### ISSUE TITLE
Get blob content w/o using blob operation from the FLDict input of the PredictiveModel callback

### ISSUE THREAD

**Issue by pasin** [couchbase/couchbase-lite-core#654]
Moved the discussion from #649 to its own ticket. 

Currently to access the blob content of the FLDict input, we need to use blob operation. However from CBL API, it's not obvious to know that the blob operation is not needed. If the blob content cannot be accessed automatically, shall we have the c4db object as a parameter on the callback so that CBL can use that to get the blob content?

**Comment by snej** [comment]
There are legitimate reasons to treat the blob dictionary like a regular dictionary, for instance if the query wants to access the `content_type` or `length` property. So the problem is knowing when it's OK to convert the dict into the blob data. The `BLOB` operator makes this explicit.

Maybe it could be converted when the blob dict is seen as a value in the dictionary passed to the prediction function. Since the binding code already has to do a bunch of conversions on the input data (like creating numeric vectors), that would seem a reasonable place.

I can definitely add the db as a parameter to the callback.

**Comment by pasin** [comment]
I think it totally makes sense to let the binding convert the `blob` dictionary to the blob object, which requires the db as a parameter in the callback.

**Comment by snej** [comment]
Done -- the callback is now passed the `C4BlobStore`. I decided not to pass the `C4Database`, because that would make it possible for a callback function to write to the database or run another query, which would be disastrous since the callback is being invoked from within a SQLite query already.

**Comment by snej** [comment]
Changed the callback to take the `C4Database` instead, since the bindings need it to be able to instantiate their Dict and Array objects.
