### ISSUE TITLE
Delete fails with default conflict scenario

### ISSUE THREAD

**Issue by sridevi-15** [couchbase/couchbase-lite-core#689]
### CBL version : 2.5.0
iOS : 2.5.0-175
.net : 2.5.0-144
Android: 2.5.0-147

### Steps to reproduce : 
        1. Create docs in CBL.
        2. Replicate docs to SG with push_pull and continuous False
        3. Wait until replication is done and stop replication
        4. update doc in Sg in one thread and delete doc in CBL in another thread(simultaneous tasks)
        5. Start the replication with same configuration as step 2
        6. Verify delete wins

### Actual : 
1. All the docs appear back to CBL after replication and Docs still exist on both SGW and CBL

### Expected:
Docs deleted at step #4 on CBL , it should get deleted on both CBL and SGW as delete has to win with default conflict resolver

### Regression test : 
https://github.com/couchbaselabs/mobile-testkit/blob/master/testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests/test_replication.py#L1301

### Tests that are failing:
test_default_conflict_scenario_delete_wins[cbl-True-1]
test_default_conflict_scenario_delete_wins[cbl-False-1]
test_default_conflict_scenario_delete_wins[cbl-False-5]

### Command to run test : 
pytest -s -rsx -k test_default_conflict_scenario_delete_wins[cbl-True-1] --timeout 1800 --liteserv-version=2.5.0-147 --liteserv-host=localhost --liteserv-port=8080  --sync-gateway-version=2.5.0-204 --mode=cc --server-version=6.0.1-2037 --liteserv-platform=ios --create-db-per-test=cbl-test testsuites/CBLTester/CBL_Functional_tests/TestSetup_FunctionalTests

### cbl logs : 
https://gist.github.com/sridevi-15/dc041f2ffbe7e43faed75a51e686623c

### SGW logs : 
https://gist.github.com/sridevi-15/36e843e671e75169e5f868ed2f3c50b1

**Comment by sridevi-15** [comment]
Note : default conflict resolver works for high rev id

**Comment by borrrden** [comment]
@snej Suspicious log line -> Replicator {DBWorker#16} _donePushingRev('replication_5'): That docID is not active!

**Comment by borrrden** [comment]
Also how do you put in these commands because this one says iOS test server for 2.5.0-147 does not exist.

**Comment by borrrden** [comment]
Instead of messing around trying to get `pytest` to work correctly I made a simple interactive test for this that so far has not reproduced the issue:

The automatic part does this

1. Create a document named "resolve"
2. Run a one-shot push/pull replication
3. Wait 5 seconds
4. Run a one-shot push/pull replication
5. Verify that the document is null when retrieving from the local database

While on the manual side I wait until the automated process goes to step 3 and then use Postman to delete the "resolve" document from Sync Gateway before step 4.  After the automated part finishes, do a GET and verify that the result is "not found" with "deleted" as the reason.

It all works just fine.  Is there any other information you can add?  What is the "True" part of this test's parameters?

**Comment by borrrden** [comment]
@sridevi-15 Why is this error in the middle -> 

> 2019-02-02T19:52:25.380Z [ERR] 401 Login required -- rest.(*handler).writeError() at handler.go:690
2019-02-02T19:52:25.380Z [INF] HTTP: #004:     --> 401 Login required  (1.1 ms)

**Comment by pasin** [comment]
I have updated iOS and Android to pickup the fix. Added verify tag.

**Comment by snej** [comment]
The fixes in #697 should help with this too.

**Comment by sridevi-15** [comment]
Test passed with latest build
