### ISSUE TITLE
FTS: Can't query the record total with COUNT().

### ISSUE THREAD

**Issue by thanhldnv** [couchbase/couchbase-lite-core#703]
I'm trying to get number of records match with a condition in full text search. But I get a error.
This query works well, 
`[
	"SELECT",
	{
		"WHAT": [
			[
				"count()",
				[
					".",
					"uuid"
				]
			]
		],
		"WHERE": [
			"AND",
			[
				"=",
				[
					".",
					"doc_type"
				],
				"rec"
			],
			[
				"=",
				[
					".",
					"pId"
				],
				"8d8f5426-1b35-4051-8ef4-f21437fcfdba"
			]
		]
	}
]`

But when add a condition with FTS as follow, It doesn't work.
`[
	"SELECT",
	{
		"WHAT": [
			[
				"count()",
				[
					".",
					"uuid"
				]
			]
		],
		"WHERE": [
			"AND",
			[
				"AND",
				[
					"=",
					[
						".",
						"doc_type"
					],
					"rec"
				],
				[
					"MATCH",
					"record_fts_index",
					"keyword"
				]
			],
			[
				"=",
				[
					".",
					"pId"
				],
				"bfe2970b-9be6-46f6-b9a7-38c5947c27b1"
			]
		]
	}
]`

Can you let me an idea?

**Comment by thanhldnv** [comment]
This is log of error 
[CBL] QThread(0x1b3d22d40b0) "SQLite error (code 1): statement aborts at 32: [SELECT kv_default.rowid, offsets(\"kv_default::record_fts_index\"), fl_result(count(fl_value(body, 'uuid'))) FROM kv_default JOIN \"kv_default::record_"

**Comment by borrrden** [comment]
This appears to be an issue with the correct error message coming through more than anything.  There is a limitation in SQLite that prevents us from putting FTS results in anything except for a top level WHERE or top level AND.  You could try switching the `[ "=", [ ".", "pId" ], "bfe2970b-9be6-46f6-b9a7-38c5947c27b1" ]` and `[ "MATCH", "record_fts_index", "keyword" ]` and see if that helps.

**Comment by snej** [comment]
The query converter rejects queries where the MATCH isn't at the top or in an AND, but it allows it to be in a nested AND, which is why this query passes. So it's odd that it fails at runtime, especially with a weird error. @thanhldnv, what is the exact error returned from the API? (If you're using LiteCore directly, call `c4error_getDescription`.)

**Comment by snej** [comment]
…never mind, I was able to run your query; the error is `SQLite error 1 "unable to use function offsets in the requested context"`. Which is referring to the `offsets` function that's used in the translated SQLite query:

`SELECT _doc.rowid, offsets(fts1."kv_default::byStreet"), fl_result(count(fl_value(_doc.body, 'uuid'))) FROM kv_default AS _doc JOIN "kv_default::record_fts_index" AS fts1 ON fts1.docid = _doc.rowid WHERE ((fl_value(_doc.body, 'doc_type') = 'rec' AND fts1."kv_default::record_fts_index" MATCH 'keyword') AND fl_value(_doc.body, 'pId') = 'bfe2970b-9be6-46f6-b9a7-38c5947c27b1') AND (_doc.flags & 1 = 0)`

**Comment by snej** [comment]
The weird thing is that we have a unit test "Full-text query in multiple ANDs" [in c4QueryTest.cc], which passes, despite being nearly identical in structure to this failing query.

**OH!** I just noticed that the failing query uses `count()` -- that means it's an aggregate query. The `offsets` function won't work there because it describes a single match. This is our bug, because we insert the call to `offsets` so that query accessors can discover the matched range. We should omit that in an aggregate query.
