### ISSUE TITLE
SQLite Disk I/O error deleting index.

### ISSUE THREAD

**Issue by bmeike** [couchbase/couchbase-lite-core#728]
An Android test that verifies the Index deletion API has suddenly started failing reproducibly as of commit couchbase-core-lite commit #4507e205f5c5f10ec69

Failure log enclosed.

[core-update-2019-03-27-02.txt](https://github.com/couchbase/couchbase-lite-core/files/3019163/core-update-2019-03-27-02.txt)

**Comment by snej** [comment]
```
SQLite error (code 6410): statement aborts at 12: [DROP TABLE IF EXISTS 'main'.'kv_default::index2_stat';] disk I/O error
SQLite error (code 10): statement aborts at 13: [DROP TABLE "kv_default::index2"] disk I/O error
disk I/O error (10/10)
SQLite error (code 1): statement aborts at 1: [ROLLBACK] cannot rollback - no transaction is active
cannot rollback - no transaction is active (1/1)
```

The crash is due to: `libc++abi: terminating with uncaught exception of type SQLite::Exception: cannot rollback - no transaction is active`

Backtrace looks like
```
std::terminate()+56
litecore::Transaction::~Transaction()+112
litecore::SQLiteKeyStore::deleteIndex(fleece::slice)+344
```

**Comment by borrrden** [comment]
That's the reason for the crash, but I'm more interested in the reason for the rollback which is the old "OMG NO TEMP STORE DIRECTORY" failure.  I can't explain why this would happen after the refactor when the actual temp store change happened several commits earlier.

**Comment by snej** [comment]
How do you know this is related to the temp store? I don't see anything about that in the log.

**Comment by snej** [comment]
I verified that throwing an exception from the `DROP TABLE...` statement doesn't cause a crash. It looks like for some reason in the situation above SQLite forgot it was in a transaction, so the `ROLLBACK` incorrectly failed.

The `disk I/O error` is most likely caused by the database file being deleted out from underneath SQLite. There have been a few bugs like this in our unit tests from time to time, where the test framework deletes the DB directory before the database is actually closed.

**Comment by borrrden** [comment]
Error 6410 is SQLITE_IOERR_GETTEMPPATH (a very specific and scoped error code)

**Comment by borrrden** [comment]
I am almost certain I've gotten to the bottom of this.  Fix on the fix/android_temp_dir branch.  I will have @bmeike confirm that it works.
