### ISSUE TITLE
Delta sync throws C++ exception with P2P

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#732]
Discovered via https://github.com/couchbase/couchbase-lite-net/issues/1135

The original issue talks about not being able to filter properly, but the reason it is not able to filter properly is because it doesn't survive long enough to make it to the filter.  The reason it happens only with attachments is because without attachments it is too small to create a delta.

The offending function is here

https://github.com/couchbase/couchbase-lite-core/blob/db48f678adc748f877def59636f069977f574d16/Replicator/DBWorker%2BPull.cc#L284

The error code that gets thrown is SharedKeysStateError with the message "incorrect use of persistent shared keys: not in transaction" which bubbles up from the JSON converter.

**Comment by snej** [comment]
Applying a delta shouldn't be using the database's SharedKeys if it's not in a transaction.
What's the backtrace?

**Comment by snej** [comment]
OK, I've worked out that this bug is triggered only when
* A delta is received by the puller, _and_
* The delta needs to be applied before inserting the doc, i.e. either there is a pullValidator or the delta contains a `"digest`" property, _and_
* The delta contains a new property name that's not yet in the database (and is shared-key-izable, i.e. like an identifier.)

The second condition means the delta will be applied before inserting the revision, and the third means that decoding the JSON to Fleece will fail because the database's SharedKeys can't add a new key.

None of our unit tests hit these conditions, so I need to write one that does.
FYI, I believe this same bug exists on the master branch, so the fix will need to be ported there (by hand, not as a cherry-pick.)
