### ISSUE TITLE
Reimplement pending (un-pushed) docs feature

### ISSUE THREAD

**Issue by K-Leon** [couchbase/couchbase-lite-core#745]
I know that this feature from 1.4 is still missing, but i think about implementing it myself and sending a PR if the Quality is acceptable. 

But to assess if it's doable i would need a small hint how (or if) these docs are marked in sqlite.

**Comment by snej** [comment]
Do you mean the feature to find (or count) documents that should be pushed? It's a query for documents whose `sequence` is greater than the replicator's local checkpoint. Let me explain:

Every document has a sequence number, and the database has a last-sequence counter. Whenever a document is updated, `doc.sequence = ++db.lastSequence` [pseudocode]. So the sequence is sort of an abstract timestamp of how recently a document has been modified.

A replicator stores a persistent _checkpoint_ that keeps track of the latest db sequence it's pushed. The pusher's job is, basically, to find all docs with sequences greater than this, upload them, and then update the checkpoint to the highest sequence value it's pushed.

So a `getPendingDocs` function would work like this:
1. Read the checkpoint of the replicator
2. Query for all docs whose sequence property is greater than the checkpoint's local sequence
3. Skip docs that don't match the replicator's filter

And the `isDocPending` function does step 1 and then just compares the checkpoint's local sequence with the document's sequence.

In the replicator code, step 1 is `Replicator::getLocalCheckpoint`, step 2 is `Pusher::getChanges`, step 3 is `Pusher::shouldPushRev`. But those methods have a bunch of other logic that makes them more complex, so they can't simply be copied or called separately.

I think the cleanest approach would be to add a public Replicator method to return the checkpoint's local sequence. Then the pending-docs implementation can live outside the replicator codebase. It can implement step 2 with the regular `C4Query` API. For a first pass implementation we can ignore step 3.

So! The first step is to implement a public method `C4SequenceNumber Replicator::lastPushedSequence()`. The implementation is pretty simple since fortunately the `Checkpoint` class has a thread-safe API.

The second step is to implement an API function `c4repl_lastPushedSequence` that calls it, going through the `C4Replicator` C++ class (see `C4Replicator.hh`.) Using that, any developer can implement the pending-docs functionality using public API.

**Comment by djpongh** [comment]
@pasin , thoughts?

**Comment by borrrden** [comment]
Should I migrate this?

**Comment by borrrden** [comment]
Opened [CBL-233](https://issues.couchbase.com/browse/CBL-233).  Keeping this open so that original reporter can still comment.

**Comment by snej** [comment]
This was implemented in 2.7.
