### ISSUE TITLE
Query emits null for missing properties

### ISSUE THREAD

**Issue by borrrden** [couchbase/couchbase-lite-core#759]
Given a query like the following:

```
SELECT fl_result(fl_value(_doc.body, 'shipped-on')) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'test_id') = 'select_func') AND (_doc.flags & 1 = 0) ORDER BY fl_value(_doc.body, 'shipped-on')

{"ORDER_BY":[[".shipped-on"]],"WHAT":[[".shipped-on"]],"WHERE":["=",[".test_id"],"select_func"]}
```

Any document that satisfies the WHERE condition but has no `shipped-on` property should result in an empty row `{}`.  However, what actually gets emitted is the same as if the property were present and set to null -> `{"shipped-on":null}`

**Comment by snej** [comment]
The C4QueryEnumerator's row array does contain a `null` for missing values, since Fleece arrays can't contain `MISSING`. But there is a bitmap in the enumerator that identifies which columns are missing. If you can show that this bitmap is incorrect, then we have a bug; otherwise I think what you saw is a bug in the `cblite` tool's query output.

**Comment by borrrden** [comment]
Alright I've confirmed that the latest master build takes care of this problem and there is nothing to do in LiteCore.
