### ISSUE TITLE
Pulled conflicting tombstone isn't treated as a conflict

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#781]
https://github.com/couchbase/couchbase-lite-core/pull/779/files#r283975663

**Comment by snej** [comment]
As I thought, the problem is with the document determining whether it's in conflict. The situation is that:
* the local document is at revision 2-a
* the replicator pulls a conflicting revision 2-b which is deleted
* the RevTree inserts 2-b as a branch, but doesn't consider the document conflicted because 2-b is a deletion

By the regular revision-tree rules, a deletion isn't part of a conflict, since deletions are used to end branches when resolving conflicts. So the document only has one live branch.

I need to update the logic for this case where the deletion is a remote rev ... but without breaking the usage of deletions to end branches in the regular case. Hm.

**Comment by jayahariv** [comment]
closing since the #779 is merged
