### ISSUE TITLE
Sample code or higher-level docs

### ISSUE THREAD

**Issue by adamski** [couchbase/couchbase-lite-core#80]
I know this is still under heavy development, just wondered if there was some example code anywhere for e.g. setting up the manager, creating a database, creating documents, replicating etc? 

Looking forward to be able to use this in C++ projects!

**Comment by snej** [comment]
Great question. So far we haven't had much of a chance to groom LiteCore for direct use by developers, with stuff like overview docs or sample code.

At this point, the default answer is to look at the unit test code in `C/tests`, especially c4Test.cc. There's no manager; to create or open a database just call `c4db_open`. There are [API docs](https://couchbase.github.io/couchbase-lite-core/C/html/modules.html); I need to regenerate them, but they're pretty accurate for the basic CRUD stuff.

You can also look at the implementation of Couchbase Lite 2.0 for reference; there's honestly not that much code there. In Objective-C, [CBLDatabase.mm](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLDatabase.mm) and [CBLDocument.mm](https://github.com/couchbase/couchbase-lite-ios/blob/feature/2.0/Objective-C/CBLDocument.mm) (each under 500 LOC) are the best places to start.

**Comment by adamski** [comment]
Thanks, I'll take a look in those files. I'd like to use the C++ classes rather than the C API. Or would you advise against this? 

BTW what does the C4 prefix stand for?

**Comment by snej** [comment]
It's certainly appealing to use the C++ API. We have a C API mostly because C++ APIs have serious binary compatibility issues, and because automated bindings to other languages only support C.

I've tried to make the C API layer just a wrapper that doesn't introduce new functionality of its own; if there's anything like that left, it should be fixed.

But the C++ API is still considered more of an internal thing, and it's more likely to change incompatibly over time. (Right now the C API is in flux too, but it will get locked down later on in development.)

**Comment by snej** [comment]
Oh, and "C4" was originally a contraction of "CBForest", the original name of this library in Couchbase Lite 1.x when it was just being used with ForestDB databases. More recently I've backronymed it as "Couchbase Core C Client".

**Comment by borrrden** [comment]
Actually, C4 stands for "It's going to blow up like a pile of C4 and fail."  Just kidding, see the explanation above.
