### ISSUE TITLE
Can't query the records has the % character with LIKE operator.

### ISSUE THREAD

**Issue by thanhldnv** [couchbase/couchbase-lite-core#807]
Hi Team.

I have some records that has the % character, and i want to query these records so I used LIKE operator. But it seems it returns all records. I know we have to escape, but i couldn't found any document for escaping of couchbase-lite-core. I tried by preceding them with a backslash (\) but it doesn't work.

So I create this issue to get an advice.

Thank for your help.

**Comment by snej** [comment]
The LIKE operator is implemented in SQLite. According to the [docs](https://sqlite.org/lang_expr.html#like), the only way to have a literal `%` in the pattern is to use the optional `ESCAPE` clause specifying an escape character.

Unfortunately our query generator doesn't include an `ESCAPE` clause ... so I don't think there is currently any way to match a literal `%` character with LIKE.

We should add `ESCAPE '\'` to the `LIKE` expressions the query generator creates, so that developers can escape percents with backslashes.

**Comment by borrrden** [comment]
Is the escape clause smart enough to figure out how to escape itself (for example, what if after that someone wanted to search for a backslash?)

**Comment by thanhldnv** [comment]
> Is the escape clause smart enough to figure out how to escape itself (for example, what if after that someone wanted to search for a backslash?)

I think it is necessary.

**Comment by borrrden** [comment]
Created [CBL-175](https://issues.couchbase.com/browse/CBL-175)

**Comment by thanhldnv** [comment]
> Created CBL-175
Great

**Comment by borrrden** [comment]
This fix is in 2.7.0.  Will close if I don't hear back in 7 days.
