### ISSUE TITLE
CBLite backup

### ISSUE THREAD

**Issue by ssmotra** [couchbase/couchbase-lite-core#87]
A customer should be able to keep a live backup of Couchbase Lite on an SD card within the same device as their app is running.  If a device were to become unusable, they can move the SD card to a new device and get back up and running without data loss.

**Comment by snej** [comment]
This can be done easily with a local-to-local replication. It's so simple I don't even think we need extra API for it.

**Comment by jamiltz** [comment]
Is the local to local replication a new feature only?

> Additionally, you can now replicate between two local databases. This isn't often needed, but it can be very useful. For example, you can implement incremental backup by pushing your main database to a mirror on a backup disk.

in the [2.0 docs](https://github.com/couchbaselabs/couchbase-mobile-portal/blob/master/md-docs/_20/couchbase-lite/index.md#example) seem to indicate that it is 2.0 only but just want to double check? Since that's a pretty common use case, we could have a code snippet in the docs that shows how to do local back-up and then get a handle on the generated file.

**Comment by snej** [comment]
Yes, it's a new feature.
The API actually requires that both databases be open already, so there's no need to get the destination db handle.

**Comment by snej** [comment]
This basically is local-to-local replication, which exists. Any additional functionality would be at the CBL level. I think we can close this.
