### ISSUE TITLE
Unable to set / parse cookie, occasionally leading to crash

### ISSUE THREAD

**Issue by vx8** [couchbase/couchbase-lite-core#914]
I'm receiving this log using CBLite for Swift

> 2020-02-10 21:25:17.508138+0100 MyApplication[3373:2253702] CouchbaseLite Network Verbose: {BLIPIO#23} WebSocket is hungry!
> 2020-02-10 21:25:17.508279+0100 MyApplication[3373:2253702] CouchbaseLite Network Verbose: {BLIPIO#23} ...Wrote 0 bytes to WebSocket (writeable=1)
> 2020-02-10 21:25:17.508487+0100 MyApplication[3373:2253706] CouchbaseLite Database WARNING: Couldn’t parse Expires in cookie
> 2020-02-10 21:25:17.508688+0100 MyApplication[3373:2253706] CouchbaseLite Replicator WARNING: {Repl#22} Unable to set cookie `AWSALB=A9LmneWamRVJU5JbBVAoUIUu9Q9ySyzKCcP0W74QLqAppVhTK6VIIuQ2blfrbYr905T9luOHseo5E3C479Pf9y4nNzKRxSXzyVa7wBIWvDHhTjf3kvQN9YNPxj2o; Expires=Mon`: LiteCore error 9 “Invalid cookie”
> 2020-02-10 21:25:17.509023+0100 MyApplication[3373:2253706] CouchbaseLite Replicator Verbose: {Repl#22} Set cookie: `17 Feb 2020 20:25:17 GMT; Path=/`
> 2020-02-10 21:25:17.509339+0100 MyApplication[3373:2253706] CouchbaseLite Database WARNING: Couldn’t parse Expires in cookie
> 2020-02-10 21:25:17.509573+0100 MyApplication[3373:2253706] CouchbaseLite Replicator WARNING: {Repl#22} Unable to set cookie

We noticed this is usually just logged as a warning but sometimes it leads the app to a sudden crash.

Is this a known bug or is there something we have to double check in our server side config?

Thank you

**Comment by snej** [comment]
>`Unable to set cookie AWSALB=A9LmneWamRVJU5JbBVAoUIUu9Q9ySyzKCcP0W74QLqAppVhTK6VIIuQ2blfrbYr905T9luOHseo5E3C479Pf9y4nNzKRxSXzyVa7wBIWvDHhTjf3kvQN9YNPxj2o; Expires=Mon: LiteCore error 9 “Invalid cookie”`
>`2020-02-10 21:25:17.509023+0100 MyApplication[3373:2253706] CouchbaseLite Replicator Verbose: {Repl#22} Set cookie: 17 Feb 2020 20:25:17 GMT; Path=/`

The cookie is somehow being split into two headers. I've never seen that before. Do you have some middleware in between client and Sync Gateway? (I'm guessing AWS based on the cookie name.)

**Comment by viperozza** [comment]
Yes correct, we have an AWS LB as a middleware between SG and CBL clients

**Comment by vx8** [comment]
Yes correct, we have an AWS LB as a middleware between SG and CBL clients

**Comment by snej** [comment]
It kind of looks like the Set-Cookie header got split in two at the comma in the date; that is,

`Set-Cookie: AWSALB=A9LmneWamRVJU5JbBVAoUIUu9Q9ySyzKCcP0W74QLqAppVhTK6VIIuQ2blfrbYr905T9luOHseo5E3C479Pf9y4nNzKRxSXzyVa7wBIWvDHhTjf3kvQN9YNPxj2o; Expires=Mon, 17 Feb 2020 20:25:17 GMT; Path=/`

got turned into

`Set-Cookie: AWSALB=A9LmneWamRVJU5JbBVAoUIUu9Q9ySyzKCcP0W74QLqAppVhTK6VIIuQ2blfrbYr905T9luOHseo5E3C479Pf9y4nNzKRxSXzyVa7wBIWvDHhTjf3kvQN9YNPxj2o; Expires=Mon`
`Set-Cookie: 17 Feb 2020 20:25:17 GMT; Path=/`

HTTP 1.1 does say that multiple headers with the same name are equivalent to a single header with those values concatenated with commas. It kind of looks as though something here used that rule in reverse, taking a single header and splitting it into two at a comma. (In any case, the latest version of the spec, RFC7230, says that the Set-Cookie header is an exception to this rule because it commonly appears in multiples but does not allow commas.)

Ah, found it. It's in the iOS codebase, CBLWebSocket.mm at line 394:
```obj-c
    NSString* cookie = headers[@"Set-Cookie"];
    if ([cookie containsString: @", "]) {
        // CFHTTPMessage incorrectly merges multiple Set-Cookie headers. Undo that:
        NSMutableDictionary* newHeaders = [headers mutableCopy];
        newHeaders[@"Set-Cookie"] = [cookie componentsSeparatedByString: @", "];
        headers = newHeaders;
    }
```
The problem is that, in this case, the comma in a date string is _not_ a place to separate Set-Cookie header values...

**Comment by snej** [comment]
Yuck. I guess a heuristic we can use is to split the header _only_ if the comma is followed by something that looks like `name=` (i.e. regex `\s*\w+=`).

**Comment by snej** [comment]
Moved to Jira: https://issues.couchbase.com/browse/CBL-681
