### ISSUE TITLE
Replication occasionally fails with POSIX error 5 "Input/output error"

### ISSUE THREAD

**Issue by victorbergeronsemi** [couchbase/couchbase-lite-core#944]
Hello all,

I’ve recently started seeing a new issue with my replications. This is the driver code I’m running:

```
#include <iostream>
#include <thread>
#include "fleece/Fleece.hh"
#include "fleece/Mutable.hh"
#include "CouchbaseLite.hh"
int main() {
CBLError error;
CBLDatabaseConfiguration configDB = {"", kCBLDatabase_Create};
CBLDatabase* db = CBLDatabase_Open(“wss-pull”, &configDB, &error);
CBLReplicatorConfiguration config = {};
CBLReplicator *repl = nullptr;
config.database = db;
config.replicatorType = kCBLReplicatorTypePull;
config.endpoint = CBLEndpoint_NewWithURL(“wss://api.xxx.xxx.com/xxx”);
config.authenticator = CBLAuth_NewBasic(“xxx”, “xxx”);
repl = CBLReplicator_New(&config, &error);
CBLReplicator_Start(repl);
CBLReplicatorStatus status;
while ((status = CBLReplicator_Status(repl)).activity != kCBLReplicatorStopped) {
std::this_thread::sleep_for(std::chrono::milliseconds(100));
}
std::cerr << “Finished with activity=” << status.activity
<< “, error=(” << status.error.domain << “/” << status.error.code << “)\n”;
return 0;
}
```
and, while most replications complete successfully, occasionally a replication will return the following:
```
14:23:50.620610| [DB]: {Shared#1}==> class litecore::DataFile::Shared 0000021D72F4E920 @0000021D72F4E920
14:23:50.621638| [DB]: {Shared#1} instantiated on Y:\xxx\host\build-apr16-Win-Converted-Release\bin\wss-pull.cblite2\db.sqlite3
14:23:50.621979| [DB]: {DB#2}==> class litecore::SQLiteDataFile .\wss-pull.cblite2\db.sqlite3 @0000021D72F4FFB0
14:23:50.622121| [DB]: {DB#2} Opening database
14:23:50.653035| Seeding the mbedTLS random number generator...
14:23:50.655177| [Actor]: Starting Scheduler<0000021D72FA0F50> with 10 threads
14:23:50.657802| [DB]: {DB#3}==> class litecore::SQLiteDataFile .\wss-pull.cblite2\db.sqlite3 @0000021D72FA1A00
14:23:50.657995| [DB]: {DB#3} Opening database
14:23:50.683318| [DB]: {DB#4}==> class litecore::SQLiteDataFile .\wss-pull.cblite2\db.sqlite3 @0000021D72FE5F00
14:23:50.683574| [DB]: {DB#4} Opening database
14:23:50.692127| [Sync]: {Repl#5}==> class litecore::repl::Replicator .\wss-pull.cblite2\ ->wss://api.xxx.xxx.com:443/xxx/_blipsync @0000021D73017F08
14:23:50.692346| [Sync]: {Repl#5} Pull=one-shot, Options={{auth:{password:"********", type:"Basic", username:"xxx"}}}
14:23:50.692582| [Sync]: {C4Replicator#6}==> class c4Internal::C4RemoteReplicator 0000021D72FD7130 @0000021D72FD7130
14:23:50.692722| [Sync]: {C4Replicator#6} Starting Replicator {Repl#5}
14:23:50.694507| [Sync]: {Repl#5} Scanning for pre-existing conflicts...
14:23:50.694624| [Sync]: {Repl#5} Found 0 conflicted docs in 0.001 sec
14:23:50.697373| [Sync]: {Repl#5} No local checkpoint 'cp-mfZF2f61VKy61f0gHy0v5j9xkHQ='
14:23:51.523185| [Sync]: {Repl#5} Connected!
14:23:51.523297| [Sync]: {Repl#5} now busy
14:23:51.523368| [Sync]: {C4Replicator#6} State: busy, progress=0.00%
14:23:51.523491| [Sync]: {Puller#7}==> class litecore::repl::Puller ->wss://api.xxx.xxx.com:443/xxx/_blipsync @0000021D7303A278
14:23:51.523732| [Sync]: {Puller#7} Starting pull from remote seq 
14:23:51.616838| [Sync]: {Repl#5} No remote checkpoint 'cp-mfZF2f61VKy61f0gHy0v5j9xkHQ='
14:23:51.621753| [Sync]: {RevFinder#8}==> class litecore::repl::RevFinder ->wss://api.xxx.xxx.com:443/xxx/_blipsync @0000021D7303A6C8
14:23:51.622058| [Sync]: {RevFinder#8} Received 26 changes (seq '207'..'290')
14:23:51.622596| [Sync]: {RevFinder#8} Responded to 'changes' REQ#1 w/request for 26 revs in 0.000250 sec
14:23:51.722513| [Sync]: {Puller#7} Caught up with remote changes
14:23:51.724482| [Sync]: {C4Replicator#6} State: busy, progress=0.00%
14:23:51.744679| [DB]: {DB#9}==> class litecore::SQLiteDataFile .\wss-pull.cblite2\db.sqlite3 @0000021D73181A80
14:23:51.745005| [DB]: {DB#9} Opening database
14:23:51.753288| [Sync]: {Inserter#10}==> class litecore::repl::Inserter ->wss://api.xxx.xxx.com:443/xxx/_blipsync @0000021D730F2DB8
14:23:51.753586| [Sync]: {Inserter#10} Inserted   9 revs in   9.64ms (  934/sec) of which 99.8% was commit
14:23:51.816551| [WS] ERROR: mbedTLS(C): mbedtls_ssl_fetch_input() returned -76 (-0x004c)
14:23:51.816747| [WS] ERROR: mbedTLS(C): ssl_get_next_record() returned -76 (-0x004c)
14:23:51.816863| [WS] ERROR: mbedTLS(C): mbedtls_ssl_read_record() returned -76 (-0x004c)
14:23:51.816987| [WS] WARNING: ClientSocket got POSIX error 5 "Input/output error"
14:23:51.817283| [WS]: {BuiltInWebSocket#11}==> class litecore::websocket::BuiltInWebSocket wss://api.xxx.xxx.com:443/xxx/_blipsync @0000021D72FD7600
14:23:51.817513| [WS] ERROR: {BuiltInWebSocket#11} Unexpected or unclean socket disconnect! (reason=errno 5)
14:23:51.817887| [Sync]: {Repl#5} Connection closed with errno 5: "Input/output error" (state=2)
14:23:51.818031| [Sync] ERROR: {Repl#5} Got LiteCore error: POSIX error 5 "Input/output error"
14:23:51.835840| [Sync]: {Inserter#10} Inserted   8 revs in   2.31ms ( 3457/sec) of which 99.2% was commit
14:23:51.924636| [Sync] ERROR: {C4Replicator#6} State: busy, progress=65.38%, error=POSIX error 5 "Input/output error"
14:23:51.924849| [Sync] WARNING: No listener to receive error from CBLReplicator 0000021D72FD6F00: POSIX error 5 "Input/output error"
14:23:51.925031| [Sync]: {Repl#5} now stopped
14:23:51.925095| [Sync]: BLIP sent 3 msgs (168 bytes), rcvd 19 msgs (11945 bytes) in 0.402 sec. Max outbox depth was 1, avg 1.00
14:23:51.926914| [DB]: {DB#4} Closing database
14:23:51.927264| [DB]: {DB#9} Closing database
14:23:51.927412| [Sync] ERROR: {C4Replicator#6} State: stopped, progress=65.38%, error=POSIX error 5 "Input/output error"
14:23:51.927584| [Sync] WARNING: No listener to receive error from CBLReplicator 0000021D72FD6F00: POSIX error 5 "Input/output error"
Finished with activity=0, error=(2/5)
```
More info:
This has only been seen on Windows and with TLS/WSS connections. I used CMake to compile.
I’ve gotten this result both on Windows running on a VM inside a Mac, and on a native Windows machine. The DB being transferred is not particularly large and system assets are not being over-utilized.
I’m using very recent versions of LiteC/Core but not the very latest.
I’d say this interruption happens around 10% of the time for me. Running the same script again will normally properly finish the replication of the DB.

Thanks in advance.

**Comment by victorbergeronsemi** [comment]
Any ideas on this?

[A similar bug report ](https://github.com/espressif/esp-idf/issues/434) points to a connection timeout error, and it does in fact look like that could be the case, but I'm not sure what could be causing it here.

Please let me know if I can provide any more details.

Thanks again @snej @borrrden.

**Comment by borrrden** [comment]
I don't think it is because of a timeout necessarily.  It looks like that code in the downstream ticket uses the built in send and receive functions, while we have installed our own.  Our error conversion is probably still on the native side.  Could you run again with a debug build and the log settings for the "WS" domain (`c4log_getDomain("WS", false)`) set to debug.  This will output a lot but the interesting bits will be around the error messages above.

**Comment by victorbergeronsemi** [comment]
@borrrden 
After updating to latest Core and making minor adjustments, I can no longer reproduce the above problem even after extensive testing. If it ever comes back I will re-open this issue and supply the above information. Thanks.

**Comment by danielpaull** [comment]
I'm having this same issue.  I've built Couchbase Lite C on Windows 10 with VS 2017 from the head of master and get this message almost every time when starting the replicator against a new database.  There was no real resolution to this issue, and I am using the latest Core as far as I can tell - can you tell me which versions of Couchbase Lite Core and Couchbase Lite C you were using that seemed to work?

**Comment by ionutcosminmihaipfa** [comment]
I'm also having this issue and it's reproducing in 100% of cases inside an UWP application. Any ideas what would be the cause?

```
BLIP[->wss://nameserver.com:443/db/_blipsync] performNextMessage
task 3 calling Actor<0000014833A09890>mbedTLS(C): mbedtls_ssl_fetch_input() returned -76 (-0x004c)
mbedTLS(C): ssl_get_next_record() returned -76 (-0x004c)
Pull->wss://nameserver.com:443/db/_blipsync performNextMessage2
mbedTLS(C): mbedtls_ssl_read_record() returned -76 (-0x004c)
ClientSocket got POSIX error 5 "Input/output error"
Received -1 bytes from socket 1
task 6 calling Actor<0000014833F28600>Close with error
```

**Comment by victorbergeronsemi** [comment]
Re-opening issue. @ionutcosminmihaipfa I was getting this error only on Windows, are you as well?

**Comment by ionutcosminmihaipfa** [comment]
> 
> 
> Re-opening issue. @ionutcosminmihaipfa I was getting this error only on Windows, are you as well?

Yes, on Windows(UWP) only.

**Comment by borrrden** [comment]
The only errors I've seen here are errors which look network related.  Even the latest comments only show messages that say things like "I/O error" and "receive failed".  I don't see any indication of a core bug here at the moment.  Is your firewall being overly aggressive and blocking outgoing network traffic for the application you are trying to use?

**Comment by ionutcosminmihaipfa** [comment]
Yes, it's looks like the problem comes from mbedtls, I opened the [issue ](https://github.com/ARMmbed/mbedtls/issues/3873)there. I guess we can close this.

**Comment by borrrden** [comment]
I will leave it open a bit longer to see if downstream pushes back on it for an action item here.  Note that we *have* modified things but I'm not sure if it is in the area of the problem or not.

**Comment by gilles-peskine-arm** [comment]
Hi, Mbed TLS developer here. At first glance, this looks like a bug in the underlying socket implementation and not in Mbed TLS. Apparently Mbed TLS receives the error code EIO. This is a fatal error, not a “try again” error, so closing the connection is correct. That being said, if there's a commonly deployed platform where EIO should be treated as “try again”, maybe the platform code in Mbed TLS should include a workaround for this platform. We'd need to find out exactly how to reproduce the problem though, and to figure out a workaround that doesn't break other platforms.

**Comment by ionutcosminmihaipfa** [comment]
It's a bug coming from [sockpp](https://github.com/couchbasedeps/sockpp/blob/8dad5c3c2dc7e5b926bcf4e2fb3ec272dc85dff1/src/mbedtls_context.cpp#L401), the implementation handles `WSAEWOULDBLOCK `as default and it should be handled as `EWOULDBLOCK`.

**Comment by borrrden** [comment]
Migrated to [CBL-1438](https://issues.couchbase.com/browse/CBL-1438)

**Comment by danielpaull** [comment]
I did find a bug that had to do with checking for a POSIXs error code, but the code was being given a platform specific (windows) error code.  Correcting it fixed my problems.  I've been meant to report it but it slipped my mind.  Let me go digging through my notes.

**Comment by danielpaull** [comment]
From my notes at the time (below) it looks like the comments above echo what I found at the time, and so would be the same problem.

"There seems to be confusion over error return codes.  POSIX errors, like EWOULDBLOCK are being used, but I found that the underlying read function returns platform specific codes like WSAEWOULDBLOCK on Windows.  This means that for a blocking read that returns early because data wasn't ready to be read (that's the purpose of those two codes) would be treated as the wrong error.  Unfortunately in the code they use a switch statement and the default case returns the -76 code that we see in the logs, where as for WSAEWOULDBLOCK it should translate to a "retry" error and the read schedule to be done again.  This completely explains why putting in a delay masked the problem - waiting just a little bit meant that the data was ready to be read.  It also explains why this only occurs when there is a large amount of data being returned because there would be a longer latency before there was data on the socket to be read."

**Comment by ionutcosminmihaipfa** [comment]
> 
> 
> From my notes at the time (below) it looks like the comments above echo what I found at the time, and so would be the same problem.
> 
> "There seems to be confusion over error return codes. POSIX errors, like EWOULDBLOCK are being used, but I found that the underlying read function returns platform specific codes like WSAEWOULDBLOCK on Windows. This means that for a blocking read that returns early because data wasn't ready to be read (that's the purpose of those two codes) would be treated as the wrong error. Unfortunately in the code they use a switch statement and the default case returns the -76 code that we see in the logs, where as for WSAEWOULDBLOCK it should translate to a "retry" error and the read schedule to be done again. This completely explains why putting in a delay masked the problem - waiting just a little bit meant that the data was ready to be read. It also explains why this only occurs when there is a large amount of data being returned because there would be a longer latency before there was data on the socket to be read."

Can you recall if after this issue it followed another that made the connection to disconnect periodically with an error like the one below?

```
ClientSocket got POSIX error 140 "A non-blocking socket operation could not be completed immediately.
Received 18446744073709551615 bytes from socket <- That number is actually a misprinted -1
Unexpected or unclean socket disconnect! (reason=Network error 3)
sent 148 bytes, rcvd 58, in 0.326 sec (454/sec, 178/sec)
Connection closed with Network error 3: "connection timed out" (state=2)
```

**Comment by danielpaull** [comment]
Apologies for the late response - I missed the notification on Github.

Looking back through some records from other developers, back in April we say this sort of bnehavior, which is similar:

`22:13:57.615972| [Sync]: {Repl#5} Push=one-shot, Pull=one-shot, Options={{}}
22:13:57.623401| [Sync]: {Repl#5} Scanning for pre-existing conflicts...
22:13:57.625209| [WS] WARNING: ClientSocket got POSIX error 140 "A non-blocking socket operation could not be completed immediately.
"
22:13:57.631865| [Sync]: {Repl#5} Found 0 conflicted docs in 0.002 sec
22:13:57.633835| [WS]: {BuiltInWebSocket#7}==> class litecore::websocket::BuiltInWebSocket ws://***:4984/***/_blipsync @000001F02E2908E0
22:13:57.638405| [WS] WARNING: {BuiltInWebSocket#7} Unexpected or unclean socket disconnect! (reason=Network error, code=3)
22:13:57.641659| [Sync]: {Repl#5} No local checkpoint 'cp-Sbflof9lxRSvI5h9tu5m8Ji+0AU='
22:13:57.651544| [Sync]: {Repl#5} Connection closed with Network error 3: "connection timed out" (state=1)
22:13:57.658005| [Sync] ERROR: {Repl#5} Got LiteCore error: Network error 3 "connection timed out"`

Apparently that was fixed by updating to a more recent version of CouchbaseLiteCore than whatever the submodule reference was for whatever branch was being built at the time.  Sorry I can't be more specific!

I had another problem when trying to use Nginx as a reverse proxy for Sync Gateway and that was reported as a failure to upgrade the socket.  That turned out to be in CouchbaseLiteCore/Networking/HTTP/HTTPLogic.cc, around line 315 it checks for an "Upgrade" (uppercase U) header, but Nginx was sending"uprade" (all lower case), which is allowed by the standard.

Other problems I had at the time for the record, which was around the start of August, so these are probably fixed:

1) The _cbl_deprecated macro in include/cbl/CBL_Compat.h for Windows was not consistent with other platforms and needed to be modified.

2) The exported symbols in src/CBL.def were not up to date.

I hope that helps!  Next time I need to get my fingers into Couchbase Line C, I'll try building from master and see what happens!

**Comment by ionutcosminmihaipfa** [comment]
Thanks for the reply, I found the problem for the 140 error [here ](https://github.com/couchbase/couchbase-lite-core/issues/1082), which soon will have a Pull request.

I think this issue should now be closed as it was solved by [this PR](https://github.com/couchbasedeps/sockpp/pull/6).

**Comment by borrrden** [comment]
Sure, if @victorbergeronsemi agrees!

**Comment by victorbergeronsemi** [comment]
Many thanks for the support, cheers.
