### ISSUE TITLE
couchbase library crash on Android 11

### ISSUE THREAD

**Issue by nguoithichkhampha** [couchbase/couchbase-lite-core#983]
Hi, I'm testing my project on Android 11 and get this log then app crashed
<img width="1349" alt="Screen Shot 2020-05-29 at 00 04 10" src="https://user-images.githubusercontent.com/1573602/83214617-359b8000-a18f-11ea-8739-99804ad931eb.png">

it relates to Android icu library. the log error from file couchbase-lite-core/LiteCore/Android/unicode/ndk_icu.c
I tried to find root cause and see. Google has changed something in android runtime. here is folder structure of android runtime on Android 10. we can see library libicui18n.so and libicuuc.so
<img width="442" alt="old_structure" src="https://user-images.githubusercontent.com/1573602/83214762-8b702800-a18f-11ea-9a98-b97f00657bd0.png">

and here on Android 11. Don't see library of icu
<img width="443" alt="new_structure" src="https://user-images.githubusercontent.com/1573602/83214777-962abd00-a18f-11ea-8d6f-07f96170b6b2.png">

**Comment by borrrden** [comment]
If it got as far as that error message then it must have found something in `/system/usr/icu` but then not found the libraries which suggested that rather than being removed that they have been moved elsewhere.  Do you see them anywhere?  I'll check downstream as well...

**Comment by borrrden** [comment]
Looks like possibly it might have been renamed to `libandroidicu` as well

**Comment by nguoithichkhampha** [comment]
where is code find library icu ? I checked folder of android runtime
`/apex/com.android.runtime/lib` on Android 10 and Android 11 has the difference
Exist icu library in that folder with Android 10 and don't see with Android 11
I also hear that Google has something change on android runtime .
For long term, call to system library by **dlopen** have many risk. you should use an official method .
(build static library of icu for Android or something like that)

**Comment by borrrden** [comment]
This is the official method until the NDK team finishes their official wrapper.  They told me so themselves.  I am not able to reproduce this with a newly created Android R emulator.  I wrote a small test case to see what would happen and `dlopen` returns perfectly fine.  Maybe there is something odd with your emulator sysimage?  Different verison?  I also see the new structure but the official Android ICU docs say that it should be backwards compatible.

**Comment by nguoithichkhampha** [comment]
ah, wait. android 11 system image has the feature support run apps for arm on x86 image. 
actually, I'm running app build for armv7 on emulator x86. may it affects ? Can you try this way.

**Comment by borrrden** [comment]
Makes no difference.  All 4 architectures I tried succeeded.  I think something might be going on in your environment.  Here is the test I used anyway:  

[ndk_icu_bug.zip](https://github.com/couchbase/couchbase-lite-core/files/4700193/ndk_icu_bug.zip)

**Comment by nguoithichkhampha** [comment]
seems you run this test by the way call executable file directly and it will not run via android runtime. Can you try to test with android app ?

**Comment by borrrden** [comment]
If you provide a test case I will run it.  I ran our suite of Android query tests which should hit this at some point and there were no failures on the R emulator.

**Comment by nguoithichkhampha** [comment]
okay, I will send you my project test.

**Comment by nguoithichkhampha** [comment]
Update: I run your test successful on my side.

**Comment by nguoithichkhampha** [comment]
I just created a fresh testing project. Now I can confirm, the root cause is run arm app on x86 image of Android 11. if I build native library support for x86 abi, the error not happens.
Here is apk file of arm app, you can try to install on emulator of Android 11 . you should see log error 
[app-debug.apk.zip](https://github.com/couchbase/couchbase-lite-core/files/4700713/app-debug.apk.zip)
anyway, this error does not relate to couchbase. Thanks for your support.

**Comment by borrrden** [comment]
Good to hear that you got to the bottom of it.

**Comment by borrrden** [comment]
FYI the NDK person I was in contact with suggested you file a bug report about this -> https://developer.android.com/studio/report-bugs#emulator-bugs

**Comment by nguoithichkhampha** [comment]
great, thank you.

**Comment by nguoithichkhampha** [comment]
@borrrden , while talking with google developer. they said that . for android application target API 29 or above.  dlopen of icu library will return null
https://android.googlesource.com/platform/bionic/+/refs/heads/master/tests/dlext_test.cpp#247
`

TEST(dlfcn, dlopen_system_libicuuc_android_api_level_28) {
--
  | android_set_application_target_sdk_version(28);
  | ASSERT_TRUE(dlopen(PATH_TO_SYSTEM_LIB "libicuuc.so", RTLD_NOW) != nullptr);
  | ASSERT_TRUE(dlopen(PATH_TO_SYSTEM_LIB "libicui18n.so", RTLD_NOW) != nullptr);
  | }
  |  
  | TEST(dlfcn, dlopen_system_libicuuc_android_api_level_29) {
  | android_set_application_target_sdk_version(29);
  | ASSERT_TRUE(dlopen(PATH_TO_SYSTEM_LIB "libicuuc.so", RTLD_NOW) == nullptr);
  | ASSERT_TRUE(dlopen(PATH_TO_SYSTEM_LIB "libicui18n.so", RTLD_NOW) == nullptr);
  | }

`

**Comment by borrrden** [comment]
Did they also happen to say what I am supposed to do instead?  4 copies of ICU static libs is not an acceptable solution.

**Comment by nguoithichkhampha** [comment]
ah, no worry. They just confirmed . this test to check icu library in "/system/lib".
while your code find library in another location.

**Comment by rprichard** [comment]
`dlopen("libicuuc.so", RTLD_NOW)` is OK, but `dlopen("/system/lib[64]/libicuuc.so", RTLD_NOW)` is a problem because the library might be in a different path (e.g. somewhere in `/apex/...`). If the target API is low enough, then for backwards compatibility, the dynamic loader will see the attempt to open `"/system/lib[64]/libicuuc.so"` and load the library from the true location in `/apex/...`.

**Comment by borrrden** [comment]
So the former is the correct way to do it for all versions?  Or only once the target API is not "low enough" anymore?

**Comment by rprichard** [comment]
@DanAlbert

Yes, I believe the former is the correct way for all Android versions.

**Comment by DanAlbert** [comment]
Yeah, afair all of the still-supported API levels can handle the SONAME loading. That's the way to go.

**Comment by borrrden** [comment]
@DanAlbert Thanks for chiming in!  How about the header search directory?  Does `scandir("/system/usr/icu", &namelist, &filter, alphasort);` remain valid or do I need to search elsewhere (and is that version dependent?)

**Comment by DanAlbert** [comment]
Do you mean the ICU data? I wouldn't expect the headers to be on the device. I can't easily check from this machine, but I don't know what use they'd be there. The ICU libraries on the device have the data directory baked in so it isn't a thing you need to worry about, 

If you do mean the C headers, if I'm remembering correctly those can just be taken from AOSP. Digging up my old patches (https://android-review.googlesource.com/c/platform/external/icu/+/688487 and https://android-review.googlesource.com/c/platform/external/icu/+/698317, primarily), it looks like the only thing I did beyond that was a bit of work to hide unstable APIs so you don't accidentally use them :)

FWIW it has been quite a while since I've looked at ICU and there have definitely been some changes in how that's distributed. I believe the changes should have been behavior preserving aside from the location on device, but you shouldn't need to worry about the location anyway. The exact requirements as far as what headers are useful to you is something I may not be up to date on.

**Comment by borrrden** [comment]
Ah yes sorry, it is the data files!  The code (which actually I copied from AOSP it looks like) looks for what version of ICU is present on the device by checking what data files are there.  This version is used to generate the function names (e.g. `ucol_open44`)

**Comment by DanAlbert** [comment]
I'm pretty sure the answer is that you know longer need to worry about the version suffix and that the symbols are now just `ucol_open_android`, but I've sent an email to someone that should know better. I'll let you know what I hear.

**Comment by borrrden** [comment]
Thanks, if that person happens to mention what version that new suffix is applicable from then all the better.  We still support back to approximately API 21.

**Comment by DanAlbert** [comment]
Here was his advice:

> Now, for R, the ICU data file is located in /apex/com.android.i18n/etc/icu/icudt66l.dat. 
/system/usr/icu/icudt66l.dat should be a symlink pointing to /apex/com.android.i18n/etc/icu/icudt66l.dat, but it's not CTS-tested anywhere.
>
> Instead of looking at the file location, I recommend to use the stable API to get the ICU version via https://developer.android.com/reference/android/icu/util/VersionInfo#ICU_VERSION, because the ICU4J and ICU4C versions are always in sync. For M or older device, the file location should always be in /system/usr/icu/.

So that API is going to be your best bet for long-term stability, but if getting that info from Java-land isn't viable there's a fallback option that you could use so long as you're willing to accept maybe needing to make further adaptations later.

**Comment by nguoithichkhampha** [comment]
I just wanted to update latest information. After create new android emulator with official release of Android 11 sdk. we don't get this bug. before I used Android 11 sdk preview.

**Comment by mactiMirror** [comment]
I am facing a similar issue on couchbase,
 Process: com.am.cbexample, PID: 2854
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/cb.apk"],nativeLibraryDirectories=[/system/lib64/cb, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]] couldn't find "libLiteCoreJNI.so"
Do you have any idea how can i fix this? is this related to jnilibs?

**Comment by nguoithichkhampha** [comment]
@mactiMirror , your issue is different. may you don't puts libLiteCoreJNI.so to android project or put wrong location.

**Comment by mactiMirror** [comment]
@nguoithichkhampha I checked it in the lib, it is present with all these folders "arm64-v8a","x86", "x86_64","armeabi-v7a". 
could you please help me with the right location?

**Comment by borrrden** [comment]
That library is not generated by this repository.  See https://github.com/couchbase/couchbase-lite-java-common/

**Comment by mactiMirror** [comment]
@borrrden @nguoithichkhampha:- I have a sample project done in which I am using only Couchbase and facing the same issue. The issue is at line  CouchbaseLite.init(applicationContext) in my Application class.
 When I try to run the application as a normal application it works well but when I try to use it as a system app I get this error. I am unable to understand the exact cause.

**Comment by borrrden** [comment]
Once again, this has nothing to do with this repo, if you think you have found a bug with LiteCoreJNI please file an issue on the repo I linked.
